import type { Content } from "./types";

export const de: Content = {
  meta: {
    home: {
      title: "Kunz Global — Eine Gruppe. Mehrere Unternehmen. Eine Vision.",
      description:
        "Kunz Global ist eine Unternehmensgruppe, die spezialisierte Unternehmen in Landwirtschaft, Technologie, internationalem Handel und Business Services aufbaut und betreibt. Standort Uruguay, international ausgerichtet.",
    },
    businesses: {
      title: "Unsere Unternehmen — Kunz Global",
      description:
        "Das Portfolio von Kunz Global: Kunz Agrotech, Agralon, Kunz Sourcing, Renvora, Kunz Systems, KunzAkquise und Vomando — eigenständige Marken, eine verbundene Gruppe.",
    },
    about: {
      title: "Über uns — Kunz Global",
      description:
        "Europäische Wurzeln, aufgebaut in Uruguay. Wie Kunz Global spezialisierte Unternehmen in Landwirtschaft, Software, Handel und Dienstleistung entwickelt — und warum sie zusammengehören.",
    },
    contact: {
      title: "Kontakt — Kunz Global",
      description: "Kontakt zu Kunz Global für Partnerschaften, geschäftliche Anfragen oder Fragen zu einem unserer Unternehmen.",
    },
    legal: { title: "Impressum — Kunz Global", description: "Impressum und Anbieterangaben für kunzglobal.com." },
    privacy: { title: "Datenschutzerklärung — Kunz Global", description: "Wie kunzglobal.com mit personenbezogenen Daten umgeht." },
    terms: { title: "AGB — Kunz Global", description: "Allgemeine Geschäftsbedingungen von Kunz Global." },
    notFound: { title: "Seite nicht gefunden — Kunz Global", description: "Die angeforderte Seite existiert nicht." },
  },
  nav: {
    businesses: "Unternehmen",
    about: "Über uns",
    vision: "Vision",
    contact: "Kontakt",
    menu: "Menü",
    close: "Schließen",
    language: "Sprache",
    skip: "Zum Inhalt springen",
    home: "Kunz Global — Startseite",
  },
  hero: {
    eyebrow: "Unternehmensgruppe · Uruguay",
    title: ["Eine Gruppe. Mehrere Unternehmen.", "Eine Vision."],
    lead: "Kunz Global entwickelt und betreibt spezialisierte Unternehmen in Landwirtschaft, Technologie, internationalem Handel und Business Services.",
    ctaPrimary: "Unsere Unternehmen",
    ctaSecondary: "Über Kunz Global",
    sectors: ["Landwirtschaft", "Software", "Internationaler Handel", "Vertriebstechnologie", "Digital Learning", "Business Services"],
    networkAlt: "Abstraktes Netzwerk: Kunz Global im Zentrum, verbunden mit seinen Geschäftsbereichen.",
    scroll: "Scrollen",
  },
  group: {
    eyebrow: "Die Gruppe",
    title: ["Eine Plattform für den Aufbau", "spezialisierter Unternehmen."],
    lead: "Kunz Global erkennt Chancen, entwickelt Geschäftsmodelle und baut die Unternehmen, die sie umsetzen.",
    body: "Jedes Unternehmen hat seine eigene Marke, seinen eigenen Markt und seinen eigenen Fokus. Die Gruppe verbindet sie — mit gemeinsamer Technologie, operativer Erfahrung und internationalem Blick.",
    facts: [
      { label: "Standort", value: "San José, Uruguay" },
      { label: "Portfolio", value: "Sieben aktive Unternehmen" },
      { label: "Branchen", value: "Landwirtschaft · Technologie · Handel · Vertrieb" },
      { label: "Arbeitssprachen", value: "English · Español · Deutsch · Português" },
    ],
  },
  portfolio: {
    eyebrow: "Portfolio",
    title: ["Unsere", "Unternehmen."],
    lead: "Sieben Marken, jede spezialisiert auf ihr Feld. Aufgebaut und betrieben innerhalb der Gruppe.",
    viewAll: "Alle Unternehmen im Detail",
    external: "öffnet in neuem Tab",
    siteLang: { en: "Website auf Englisch", es: "Website auf Spanisch", de: "Website auf Deutsch", pt: "Website auf Portugiesisch" },
    agralonFlow: ["Anfrage", "Einsatzplanung", "Einsatz", "Bericht", "Rechnung"],
    sampleData: "Produktansicht mit Beispieldaten",
    renvoraFlow: ["Recherche", "Ansprache", "Follow-up"],
    sourcingLines: ["Rindfleisch", "Merinowolle"],
    systemsModules: ["Webplattformen", "Mobile Apps", "Automatisierung", "KI-Workflows"],
    systemsCaption: "Schematische Darstellung",
    akquiseSteps: ["Zielkundenliste", "Erstansprache", "Termin"],
    akquiseCaption: "Ablauf der Dienstleistung",
    vomando: { course: "Spanisch · Uruguay", path: "Ihr Lernpfad", pillars: ["Personalisiertes Lernen", "Lokale Alltagssprache", "KI-gestütztes Üben"], caption: "Schematische Produktansicht" },
  },
  businesses: {
    agrotech: {
      category: "Agrartechnologie",
      short: "Einsatz von Agrardrohnen und präzise Applikationsdienstleistungen für landwirtschaftliche Betriebe in Uruguay.",
      offer: "Drohnenapplikation für landwirtschaftliche Betriebe in Uruguay: Pflanzenschutz, Aussaat und fester Dünger aus der Luft, auch auf Flächen, die mit Bodenmaschinen schwer erreichbar sind.",
      cta: "Drohnenleistungen ansehen",
      long: "Kunz Agrotech ist der Agrardrohnen-Dienstleister der Gruppe. Mit einer DJI Agras T100 bringt das Unternehmen Pflanzenschutzmittel, Saatgut und festen Dünger für Betriebe in Uruguay aus, auch in Senken und auf nassen Flächen, wo Bodenmaschinen an Grenzen stoßen. Jeder Auftrag wird nach Kultur, Produkt und Zustand des Schlags eingestellt und mit den Betrieben und ihren Agraringenieuren geplant.",
      focus: ["Pflanzenschutz", "Aussaat aus der Luft", "Fester Dünger", "Schwer zugängliche Flächen"],
    },
    agralon: {
      category: "Agrarsoftware",
      short: "Die Betriebsplattform für Agrar-Dienstleister und Drohnenbetreiber — von der ersten Anfrage bis zur Rechnung.",
      offer: "Software für Agrar-Dienstleister und Drohnenbetreiber: ein Ablauf von der Kundenanfrage über Einsatzplanung und Feldarbeit bis zu Bericht und Rechnung.",
      cta: "Agralon entdecken",
      long: "Agralon bringt den Arbeitsalltag von Agrar-Dienstleistern in ein System: Anfragen, Kunden und Felder, Einsatzplanung von Piloten und Maschinen mit Wetterprüfung, die Piloten-App für die Feldarbeit (auch ohne Netz), Einsatzberichte, Angebote, Rechnungen und Zahlungen. Entstanden ist Agralon aus dem eigenen Drohnenbetrieb von Kunz Agrotech; es funktioniert unabhängig von der Drohnenmarke.",
      focus: ["Anfragen & Aufträge", "Kunden & Felder", "Planung & Wetter", "Piloten-App", "Einsatzberichte", "Angebote & Rechnungen"],
      status: "Early Access offen",
    },
    sourcing: {
      category: "Internationaler Handel & Sourcing",
      short: "Rindfleisch und Merinowolle aus Uruguay für internationale B2B-Käufer, am Ursprung beschafft und als strukturierter Handel abgewickelt.",
      offer: "Weiderindfleisch aus Uruguay (grasgefüttert) für Importeure, Großhändler und Verarbeiter, bezogen über EU-zugelassene Exportbetriebe. Ergänzt durch Merinowolle.",
      cta: "Sourcing-Angebot ansehen",
      long: "Kunz Sourcing ist das Handelsunternehmen der Gruppe und der Ansprechpartner der Käufer in Uruguay. Der Schwerpunkt ist Rindfleisch: Premium-Cuts, Verarbeitungsware und Industriefleisch, gekühlt oder gefroren, nach Spezifikation über EU-zugelassene uruguayische Exportbetriebe beschafft; Betrieb, Spezifikation und Dokumente werden vor einem Angebot bestätigt. Merinowolle ergänzt das Sortiment: Kammzug und gewaschene Wolle, auf Bestellung in einer etablierten uruguayischen Kämmerei gefertigt.",
      focus: ["Weiderindfleisch", "Premium- und Verarbeitungsware", "Merinowolle", "Export aus Uruguay"],
    },
    renvora: {
      category: "Vertriebstechnologie",
      short: "Software für Leadgenerierung, Outreach und Vertriebsautomatisierung — KI für die wiederkehrende Arbeit im B2B-Vertrieb.",
      offer: "Software für B2B-Vertriebsteams: Sie recherchiert passende Unternehmen, entwirft die erste Nachricht und hält Follow-ups nach. Wie viel automatisch läuft, entscheidet Ihr Team.",
      cta: "Renvora kennenlernen",
      long: "Renvora ist die Vertriebssoftware der Gruppe. Sie lernt, was ein Unternehmen verkauft und an wen, findet und bewertet passende Interessenten, schreibt die Ansprache und hält Follow-ups nach; wie viel davon selbstständig läuft, entscheidet das Team. Renvora ist in Entwicklung, wird zuerst für die eigenen Marken der Gruppe eingesetzt und öffnet sich über Early Access für eine kleine Zahl von B2B-Unternehmen.",
      focus: ["Interessenten-Recherche", "Ansprache", "Follow-ups", "Vertriebspipeline"],
      status: "In Entwicklung · Early Access",
    },
    systems: {
      category: "Software, Apps & Automatisierung",
      short: "Digitale Produkte, Software und Automatisierung für Unternehmen sowie technologische Entwicklung innerhalb der Kunz Global Gruppe.",
      offer: "Entwickelt digitale Produkte, Software- und Automatisierungslösungen für Unternehmen und unterstützt die technologische Entwicklung innerhalb der Kunz Global Gruppe.",
      cta: "Kunz Systems entdecken",
      long: "Kunz Systems entwickelt digitale Produkte, Software- und Automatisierungslösungen für Unternehmen und unterstützt die technologische Entwicklung innerhalb der Kunz Global Gruppe. Die Arbeit umfasst Webplattformen, mobile Apps, Prozessautomatisierung und KI-gestützte Workflows – ausgerichtet daran, wie eine Organisation tatsächlich arbeitet.",
      focus: ["Webplattformen", "Mobile Apps", "Automatisierung", "KI-Workflows"],
    },
    akquise: {
      category: "B2B-Vertrieb & Business Development",
      short: "Spezialisierter Outbound-Vertrieb für B2B-Unternehmen: Leadgenerierung, Kaltakquise und Terminierung.",
      offer: "Outbound-Vertrieb als ausgeführte Dienstleistung für B2B-Unternehmen: Recherche von Zielkunden, Erstansprache per Telefon und E-Mail, Terminvereinbarung. Eine Dienstleistung, keine Software.",
      cta: "Vertriebsleistungen ansehen",
      long: "KunzAkquise übernimmt den Outbound-Vertrieb für B2B-Unternehmen als Dienstleistung: Zielkundenprofil, Recherche von Unternehmen und Ansprechpartnern, telefonische Erstansprache nach Freigabe, E-Mail-Kampagnen mit Follow-ups, Bedarfsqualifizierung und Terminvereinbarung. Übergeben werden die vereinbarten Kontaktdaten, Gesprächsnotizen oder Termine. Während Renvora eine Software ist, die ein Team selbst nutzt, erledigt KunzAkquise die Arbeit für den Kunden.",
      focus: ["Lead-Recherche", "Telefonakquise", "E-Mail-Ansprache", "Terminvereinbarung"],
    },
    vomando: {
      category: "Technologie für Sprachenlernen",
      short: "Ein digitales Lernprodukt für Sprachen: personalisiertes Lernen, lokale Alltagssprache und KI-gestütztes Üben.",
      offer: "Ein digitales Lernprodukt für Sprachen mit personalisierten Lernpfaden, lokaler Sprache, wie sie im Alltag tatsächlich verwendet wird, und KI-gestütztem Üben. Erster Kurs: Spanisch · Uruguay.",
      cta: "Vomando entdecken",
      long: "Vomando ist das Consumer-Technology-Venture der Gruppe im Bereich Digital Learning. Das Produkt verbindet personalisierte Lernpfade mit lokaler Sprache, wie sie im Alltag tatsächlich verwendet wird, und ist für KI-gestütztes Üben ausgelegt. Der erste Kurs ist Spanisch, wie es in Uruguay gesprochen wird; weitere Sprachen und regionale Varianten sind geplant. Vomando befindet sich in Entwicklung.",
      focus: ["Personalisiertes Lernen", "Lokale Alltagssprache", "KI-gestütztes Üben", "Mobile-first"],
      status: "In Entwicklung",
    },
  },
  ecosystem: {
    eyebrow: "Ökosystem",
    title: ["Eigenständige Marken.", "Eine verbundene Gruppe."],
    lead: "Was ein Unternehmen lernt, nutzen die anderen. Der Betrieb im Feld prägt die Software. Vertriebserfahrung öffnet Märkte. Der Handel verbindet Uruguay mit Käufern im Ausland.",
    centerLabel: "Die Gruppe",
    centerText: "Kunz Global gibt die Richtung vor, stellt gemeinsame Technologie und Erfahrung bereit und entwickelt neue Ventures.",
    futureName: "Future Ventures",
    futureCategory: "In Entwicklung",
    futureText: "Neue Unternehmen werden laufend geprüft und aufgebaut. Sie erscheinen hier, sobald sie so weit sind.",
  },
  featured: {
    eyebrow: "Ausgewählte Ventures",
    title: ["Substanz,", "Unternehmen für Unternehmen."],
    items: {
      agrotech: {
        kicker: "Kunz Agrotech",
        title: "Ein Einsatztag auf dem Feld.",
        text: "Eine DJI Agras T100 auf einem abgeernteten Feld, dazu Begleitfahrzeug, Wassertank und Mischanhänger. Jeder Auftrag wird nach Kultur, Produkt und Zustand des Schlags eingestellt; die Benetzung wird mit wassersensitivem Papier geprüft.",
        alt: "DJI Agras T100 von Kunz Agrotech auf einem abgeernteten Feld in Uruguay, dahinter das Begleitfahrzeug und ein Anhänger mit Wassertank und Mischtechnik.",
      },
      agralon: {
        kicker: "Agralon",
        title: "Von der Anfrage bis zur Zahlung.",
        text: "Jeder Auftrag durchläuft dieselben Stufen. Das Büro plant, der Pilot arbeitet mit der App, Bericht und Rechnung entstehen aus den Auftragsdaten.",
        alt: "Agralon mit Beispieldaten: Dashboard mit den Aufträgen des Tages, Wetter und Feldkarte auf einem Laptop, daneben die Piloten-App auf dem Smartphone.",
      },
      sourcing: {
        kicker: "Kunz Sourcing",
        title: "Rindfleisch und Merinowolle aus Uruguay.",
        text: "Kunz Sourcing beschafft Rindfleisch nach Spezifikation des Käufers über EU-zugelassene uruguayische Exportbetriebe und Merinowolle als Kammzug und gewaschene Wolle, auf Bestellung gefertigt. Spezifikation, Dokumente und Verschiffung werden von Uruguay aus koordiniert.",
        alt: "Lager in Uruguay mit gestapelten, umreiften Wollballen für den Export.",
      },
      renvora: {
        kicker: "Renvora",
        title: "Recherche, Ansprache und Follow-up in einem Ablauf.",
        text: "Renvora findet passende Unternehmen, schreibt die erste Nachricht, hält das Gespräch am Laufen und bringt Termine in die Pipeline. Das Produkt ist in Entwicklung; Early Access steht einer kleinen Zahl von B2B-Unternehmen offen.",
        alt: "Schematischer Vertriebsablauf von der Recherche bis zum Termin.",
      },
    },
    renvoraSteps: ["Recherche", "Bewertung", "Ansprache", "Follow-up", "Termin"],
    renvoraCaption: "Schematische Darstellung",
    agralonSteps: ["Anfrage", "Koordination", "Einsatzplanung", "Einsatz", "Bericht", "Rechnung", "Zahlung"],
    agralonStepsLabel: "Der Agralon-Ablauf",
    sourcingFacts: [
      { term: "Rindfleisch", value: "Premium, Verarbeitungs- und Industrieware · gekühlt oder gefroren" },
      { term: "Bezug", value: "EU-zugelassene Exportbetriebe in Uruguay" },
      { term: "Merinowolle", value: "Kammzug · gewaschene Wolle, auf Bestellung" },
    ],
    statusLabel: "Status",
  },
  principles: {
    eyebrow: "Prinzipien",
    title: ["Was unsere Unternehmen", "verbindet."],
    items: [
      { title: "Technologie", text: "Wir setzen Technologie dort ein, wo sie die Arbeitsweise einer traditionellen Branche verändert — und ein Geschäft skalierbar macht." },
      { title: "Umsetzung", text: "Wir bauen und betreiben. Jedes Unternehmen der Gruppe leistet echte Arbeit für echte Kunden." },
      { title: "Internationale Perspektive", text: "Wir verbinden Chancen zwischen Uruguay, Lateinamerika und Märkten in Europa und darüber hinaus." },
      { title: "Langfristiger Wert", text: "Wir bauen Unternehmen auf Dauer: zuerst tragfähige Wirtschaftlichkeit, dann Wachstum." },
    ],
  },
  uruguay: {
    eyebrow: "Herkunft",
    title: ["Aufgebaut in Uruguay.", "Verbunden mit der Welt."],
    text: "Von Uruguay aus arbeitet die Gruppe: ein stabiles Land mit starker Agrarwirtschaft und offenem Zugang zu internationalen Märkten. Von hier aus arbeitet Kunz Global mit Partnern und Kunden in Lateinamerika und Europa.",
    points: [
      { title: "Operativer Standort", text: "San José, Uruguay — nah an den Feldern und am Hafen von Montevideo." },
      { title: "Europäische Wurzeln", text: "Europäischer Hintergrund und enge Verbindungen in den deutschsprachigen Raum." },
      { title: "Vier Sprachen", text: "Englisch, Spanisch, Deutsch und Portugiesisch im Tagesgeschäft." },
    ],
    globeAlt: "Globus mit Blick auf den Südatlantik, Uruguay markiert, Verbindungen nach Europa, Nordamerika und Brasilien.",
    marker: "Uruguay",
  },
  future: {
    eyebrow: "Vision",
    title: ["Wir bauen,", "was als Nächstes kommt."],
    text: "Kunz Global prüft und entwickelt laufend neue Ventures — in Branchen, in denen Technologie, sich verändernde Märkte und operative Chancen langfristiges Potenzial schaffen.",
    fields: ["Technologie", "Landwirtschaft", "Energie", "Infrastruktur", "Handel", "Dienstleistungen"],
    note: "Neue Ventures werden vorgestellt, wenn sie operativ sind. Nicht vorher.",
  },
  cta: {
    title: ["Sprechen wir darüber,", "was wir aufbauen können."],
    text: "Für Partnerschaften, geschäftliche Anfragen oder Fragen zu einem unserer Unternehmen.",
    button: "Kontakt aufnehmen",
  },
  businessesPage: {
    eyebrow: "Portfolio",
    title: ["Sieben Unternehmen.", "Eine Gruppe."],
    lead: "Jedes Unternehmen im Portfolio ist spezialisiert, tritt unter eigener Marke auf und wird innerhalb von Kunz Global betrieben.",
    focusLabel: "Schwerpunkte",
    futureLink: "Was als Nächstes kommt",
  },
  about: {
    eyebrow: "Über Kunz Global",
    title: ["Europäische Wurzeln.", "Aufgebaut in Uruguay."],
    lead: "Kunz Global ist eine Unternehmensgruppe, die spezialisierte Unternehmen entwickelt und betreibt — gegründet und geführt von Stanley Kunz in San José, Uruguay.",
    story: [
      { title: "Wo es begann", text: "Am Anfang standen ein europäischer Hintergrund und die Entscheidung, in Uruguay aufzubauen — einem Land mit starker Landwirtschaft, stabilen Institutionen und Raum für neue Geschäftsmodelle." },
      { title: "Vom Betrieb zur Technologie", text: "Die ersten Unternehmen waren operativ: Agrardienstleistungen im Feld und Handel mit Agrarprodukten. Die Arbeit in diesen Branchen zeigte, wo Software fehlt. Genau daraus ist Agralon entstanden." },
      { title: "Eine Gruppe, mehrere Spezialisten", text: "Vertrieb und Business Development wurden zu eigenen Unternehmen, dazu kamen Vertriebstechnologie, Softwareentwicklung und Sprachlerntechnologie. Heute vereint Kunz Global Landwirtschaft, Software, internationalen Handel und Business Services unter einem Dach." },
      { title: "Was als Nächstes kommt", text: "Die Gruppe steht noch am Anfang einer längeren Entwicklung. Neue Ventures kommen hinzu, wenn es eine echte Chance gibt — und die Kapazität, sie gut umzusetzen." },
    ],
    approachTitle: "Wie wir arbeiten",
    leadership: {
      eyebrow: "Führung",
      title: "Stanley Kunz",
      role: "Gründer & Direktor",
      text: "Stanley Kunz führt Kunz Global und steht persönlich für Ausrichtung und Qualität jedes Unternehmens der Gruppe — mit klaren Ansprechpartnern und direkter Kommunikation.",
      photoAlt: "Porträt von Stanley Kunz, Gründer und Direktor von Kunz Global.",
    },
    facts: [
      { label: "Sitz", value: "San José, Uruguay" },
      { label: "Unternehmen", value: "Sieben aktive Marken" },
      { label: "Felder", value: "Landwirtschaft, Software, Handel, Vertrieb" },
    ],
  },
  contactPage: {
    eyebrow: "Kontakt",
    title: ["Beginnen wir ein", "Gespräch."],
    lead: "Schreiben Sie uns kurz, worum es geht. Wir leiten Ihre Nachricht an das richtige Unternehmen weiter und antworten persönlich.",
    form: {
      name: "Name",
      company: "Unternehmen",
      email: "E-Mail",
      area: "Interessensbereich",
      areaGeneral: "Allgemein / Partnerschaften",
      message: "Nachricht",
      optional: "optional",
      submit: "E-Mail vorbereiten",
      note: "Dieses Formular öffnet Ihr E-Mail-Programm mit der vorbereiteten Nachricht. Diese Website sendet und speichert nichts.",
      success: "Ihr E-Mail-Programm sollte jetzt geöffnet sein. Falls nicht, schreiben Sie uns bitte direkt an",
      errorRequired: "Bitte füllen Sie dieses Feld aus.",
      errorEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
      mailSubject: "Anfrage über kunzglobal.com",
      send: {
        submit: "Nachricht senden",
        sending: "Wird gesendet…",
        note: "Ihre Angaben werden per E-Mail an Kunz Global übermittelt und nur zur Beantwortung Ihrer Anfrage verwendet. Details in der Datenschutzerklärung.",
        success: "Vielen Dank. Ihre Nachricht wurde gesendet. Wir antworten an die von Ihnen angegebene E-Mail-Adresse. Sie erreichen uns auch unter",
        error: "Ihre Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es erneut oder schreiben Sie uns direkt an",
      },
    },
    directTitle: "Direkter Kontakt",
    emailLabel: "E-Mail",
    phoneLabel: "Telefon",
    locationLabel: "Standort",
    location: "San José, Uruguay",
  },
  footer: {
    tagline: "Eine Gruppe. Mehrere Unternehmen. Eine Vision.",
    businesses: "Unternehmen",
    company: "Gruppe",
    legalTitle: "Rechtliches",
    legal: "Impressum",
    privacy: "Datenschutz",
    terms: "AGB",
    location: "San José, Uruguay",
    rights: "Alle Rechte vorbehalten.",
  },
  notFound: {
    title: "Diese Seite gibt es nicht.",
    text: "Möglicherweise hat sich die Adresse mit dem Relaunch von kunzglobal.com geändert.",
    back: "Zur Startseite",
  },
  legalOverrides: {
    brandsTitle: "Unternehmen und externe Websites",
    brandsText:
      "Diese Website informiert über die Unternehmen von Kunz Global. Die folgenden Websites werden eigenständig betrieben; für ihre Inhalte gelten die jeweiligen dortigen Impressen:",
    socialTitle: "Telefon und WhatsApp",
    socialText:
      "Wenn Sie uns per Telefon oder WhatsApp kontaktieren, gelten zusätzlich die Datenschutzbestimmungen des jeweiligen Anbieters (für WhatsApp: Meta Platforms, Inc.). Auf die dortige Datenverarbeitung durch den Anbieter haben wir keinen Einfluss.",
    formTitle: "Kontaktformular",
    formText:
      "Das Kontaktformular dieser Website übermittelt keine Daten an uns oder an Dritte. Es bereitet lediglich eine Nachricht in Ihrem eigenen E-Mail-Programm vor; versendet wird sie erst, wenn Sie sie dort absenden. Diese Website setzt keine Cookies, lädt ihre Schriften vom eigenen Server und verwendet keine Analysewerkzeuge.",
    formTextSend:
      "Wenn Sie das Kontaktformular absenden, werden die von Ihnen eingegebenen Angaben (Name, Unternehmen, falls angegeben, E-Mail-Adresse, Interessensbereich und Ihre Nachricht) an uns übermittelt und per E-Mail an unsere Kontaktadresse zugestellt. Übermittlung und Zustellung erfolgen über Google Apps Script und Gmail in unserem Google-Workspace-Konto (Google Ireland Ltd. / Google LLC); dabei verarbeitet Google technische Verbindungsdaten wie Ihre IP-Adresse. Wir verwenden Ihre Angaben ausschließlich zur Beantwortung Ihrer Anfrage und für eine mögliche Anschlusskommunikation, nicht für Werbung. Rechtsgrundlage ist die Anbahnung eines Vertrags bzw. unser berechtigtes Interesse an der Beantwortung von Anfragen. Die Website selbst speichert nichts; die Nachricht bleibt nur so lange in unserem Postfach, wie es für die Bearbeitung Ihrer Anfrage erforderlich ist. Diese Website setzt keine Cookies, lädt ihre Schriften vom eigenen Server und verwendet keine Analysewerkzeuge.",
    updated: "Stand: September 2026",
  },
};
