import type { Content } from "./types";

export const de: Content = {
  meta: {
    home: {
      title: "Kunz Global — Eine Gruppe. Mehrere Unternehmen. Eine Vision.",
      description:
        "Kunz Global ist eine Unternehmensgruppe, die spezialisierte Unternehmen in Landwirtschaft, Technologie, internationalem Handel und Business Services aufbaut und betreibt. Standort Uruguay, international ausgerichtet.",
    },
    businesses: {
      title: "Unsere Unternehmen — Kunz Global",
      description:
        "Das Portfolio von Kunz Global: Kunz Agrotech, Agralon, Kunz Sourcing, Renvora, Kunz Versicherung und KunzAkquise — eigenständige Marken, eine verbundene Gruppe.",
    },
    about: {
      title: "Über uns — Kunz Global",
      description:
        "Europäische Wurzeln, aufgebaut in Uruguay. Wie Kunz Global spezialisierte Unternehmen in Landwirtschaft, Software, Handel und Dienstleistung entwickelt — und warum sie zusammengehören.",
    },
    contact: {
      title: "Kontakt — Kunz Global",
      description: "Kontakt zu Kunz Global für Partnerschaften, geschäftliche Anfragen oder Fragen zu einem unserer Unternehmen.",
    },
    legal: { title: "Impressum — Kunz Global", description: "Impressum und Anbieterangaben für kunzglobal.com." },
    privacy: { title: "Datenschutzerklärung — Kunz Global", description: "Wie kunzglobal.com mit personenbezogenen Daten umgeht." },
    terms: { title: "AGB — Kunz Global", description: "Allgemeine Geschäftsbedingungen von Kunz Global." },
    notFound: { title: "Seite nicht gefunden — Kunz Global", description: "Die angeforderte Seite existiert nicht." },
  },
  nav: {
    businesses: "Unternehmen",
    about: "Über uns",
    vision: "Vision",
    contact: "Kontakt",
    menu: "Menü",
    close: "Schließen",
    language: "Sprache",
    skip: "Zum Inhalt springen",
    home: "Kunz Global — Startseite",
  },
  hero: {
    eyebrow: "Unternehmensgruppe · Uruguay",
    title: ["Eine Gruppe. Mehrere Unternehmen.", "Eine Vision."],
    lead: "Kunz Global entwickelt und betreibt spezialisierte Unternehmen in Landwirtschaft, Technologie, internationalem Handel und Business Services.",
    ctaPrimary: "Unsere Unternehmen",
    ctaSecondary: "Über Kunz Global",
    sectors: ["Landwirtschaft", "Software", "Internationaler Handel", "Vertriebstechnologie", "Versicherung", "Business Services"],
    networkAlt: "Abstraktes Netzwerk: Kunz Global im Zentrum, verbunden mit seinen Geschäftsbereichen.",
    scroll: "Scrollen",
  },
  group: {
    eyebrow: "Die Gruppe",
    title: ["Eine Plattform für den Aufbau", "spezialisierter Unternehmen."],
    lead: "Kunz Global erkennt Chancen, entwickelt Geschäftsmodelle und baut die Unternehmen, die sie umsetzen.",
    body: "Jedes Unternehmen hat seine eigene Marke, seinen eigenen Markt und seinen eigenen Fokus. Die Gruppe verbindet sie — mit gemeinsamer Technologie, operativer Erfahrung und internationalem Blick.",
    facts: [
      { label: "Standort", value: "San José, Uruguay" },
      { label: "Portfolio", value: "Sechs aktive Unternehmen" },
      { label: "Branchen", value: "Landwirtschaft · Technologie · Handel · Versicherung · Vertrieb" },
      { label: "Arbeitssprachen", value: "English · Español · Deutsch · Português" },
    ],
  },
  portfolio: {
    eyebrow: "Portfolio",
    title: ["Unsere", "Unternehmen."],
    lead: "Sechs Marken, jede spezialisiert auf ihr Feld. Aufgebaut und betrieben innerhalb der Gruppe.",
    visit: "Website besuchen",
    noSite: "Anfragen über Kunz Global",
    viewAll: "Alle Unternehmen im Detail",
    external: "öffnet in neuem Tab",
  },
  businesses: {
    agrotech: {
      category: "Agrartechnologie",
      short: "Einsatz von Agrardrohnen und präzise Applikationsdienstleistungen für landwirtschaftliche Betriebe in Uruguay.",
      long: "Kunz Agrotech ist das operative Agrartechnologie-Unternehmen der Gruppe. Es bringt Pflanzenschutz- und Betriebsmittel mit Agrardrohnen aus — präzise, dokumentiert und in enger Abstimmung mit den Betrieben und ihren Agraringenieuren.",
      focus: ["Drohnenapplikation", "Präzisionslandwirtschaft", "Dienstleistung im Feld", "Agrartechnologie"],
    },
    agralon: {
      category: "Softwareplattform",
      short: "Die Betriebsplattform für Agrar-Dienstleister und Drohnenbetreiber — von der ersten Anfrage bis zur Rechnung.",
      long: "Agralon bringt den Arbeitsalltag von Agrar-Dienstleistern in ein System: Aufträge, Kunden und Felder, Wetter, Flotte und Wartung, Einsatzberichte, Angebote und Rechnungen. Entstanden aus dem echten Drohnenbetrieb, funktioniert es im Feld — auch ohne Netz.",
      focus: ["Operations & Aufträge", "Kunden & Felder", "Wetter", "Flotte & Wartung", "Einsatzberichte", "Angebote & Rechnungen"],
    },
    sourcing: {
      category: "Internationaler Handel & Sourcing",
      short: "Verbindet Lieferanten in Uruguay mit internationalen Käufern. Aktueller Schwerpunkt: Wolle und Agrarrohstoffe.",
      long: "Kunz Sourcing ist das Handelsunternehmen der Gruppe. Es beschafft Agrarprodukte in Uruguay für internationale B2B-Käufer und koordiniert den Weg vom Lieferanten bis zur Verschiffung. Wolle ist heute der Kern; weitere Produktbereiche werden aufgebaut.",
      focus: ["Wolle", "Agrarrohstoffe", "Export aus Uruguay", "B2B-Handel"],
    },
    renvora: {
      category: "Vertriebstechnologie",
      short: "Software für Leadgenerierung, Outreach und Vertriebsautomatisierung — KI für die wiederkehrende Arbeit im B2B-Vertrieb.",
      long: "Renvora ist ein Software-Venture im Bereich Vertriebstechnologie. Es unterstützt Leadgenerierung, Outreach, CRM-nahe Prozesse und Marketing-Automatisierung mit KI, damit Vertriebsteams ihre Zeit für Gespräche nutzen statt für Routine.",
      focus: ["Leadgenerierung", "Outreach", "Vertriebsautomatisierung", "CRM-Workflows"],
      status: "In Entwicklung · Early Access",
    },
    versicherung: {
      category: "Versicherung & Risikolösungen",
      short: "Der Versicherungsbereich im Kunz-Ökosystem — gebaut auf Vertrauen, Kontinuität und langfristige Kundenbeziehungen.",
      long: "Kunz Versicherung steht für Versicherungs- und Risikolösungen innerhalb des Kunz-Ökosystems. Ein Geschäft, das auf Vertrauen und Kontinuität beruht — und genau so geführt wird.",
      focus: ["Versicherung", "Risikolösungen"],
    },
    akquise: {
      category: "B2B-Vertrieb & Business Development",
      short: "Spezialisierter Outbound-Vertrieb für B2B-Unternehmen: Leadgenerierung, Kaltakquise und Terminierung.",
      long: "KunzAkquise ist der Business-Development-Service der Gruppe. Das Unternehmen übernimmt den B2B-Outbound-Vertrieb für Firmen, die neue Kunden gewinnen wollen, ohne zuerst ein eigenes Sales-Development-Team aufzubauen: Recherche, Kaltakquise, Qualifizierung und Terminierung.",
      focus: ["B2B-Kaltakquise", "Leadgenerierung", "Terminierung", "Sales Development"],
    },
  },
  ecosystem: {
    eyebrow: "Ökosystem",
    title: ["Eigenständige Marken.", "Eine verbundene Gruppe."],
    lead: "Was ein Unternehmen lernt, nutzen die anderen. Der Betrieb im Feld prägt die Software. Vertriebserfahrung öffnet Märkte. Der Handel verbindet Uruguay mit Käufern im Ausland.",
    centerLabel: "Die Gruppe",
    centerText: "Kunz Global gibt die Richtung vor, stellt gemeinsame Technologie und Erfahrung bereit und entwickelt neue Ventures.",
    futureName: "Future Ventures",
    futureCategory: "In Entwicklung",
    futureText: "Neue Unternehmen werden laufend geprüft und aufgebaut. Sie erscheinen hier, sobald sie so weit sind.",
  },
  featured: {
    eyebrow: "Ausgewählte Ventures",
    title: ["Substanz,", "Unternehmen für Unternehmen."],
    items: {
      agrotech: {
        kicker: "Kunz Agrotech",
        title: "Präzisionslandwirtschaft, im Feld betrieben.",
        text: "Agrardrohnen, Applikationstechnik und die Logistik drumherum. Kunz Agrotech macht die Arbeit vor Ort — und diese Erfahrung fließt in alles ein, was die Gruppe für die Landwirtschaft baut.",
        alt: "Agrardrohne auf einem abgeernteten Feld in Uruguay, dahinter das Begleitfahrzeug von Kunz Agrotech und der Mischanhänger.",
      },
      agralon: {
        kicker: "Agralon",
        title: "Ein System für den ganzen Betrieb.",
        text: "Aufträge, Felder, Wetter, Flotte, Berichte und Abrechnung in einem Ablauf — am Desktop im Büro und auf dem Smartphone im Feld. Agralon ist ein zentrales Technologieprodukt der Gruppe.",
        alt: "Agralon-Software: Dashboard mit Aufträgen, Wetter und Feldkarte auf einem Laptop, daneben die Piloten-App auf dem Smartphone.",
      },
      sourcing: {
        kicker: "Kunz Sourcing",
        title: "Aus Uruguay zu internationalen Käufern.",
        text: "Wolle und Agrarrohstoffe, am Ursprung beschafft und als strukturierter B2B-Handel abgewickelt. Klare Spezifikationen, verlässliche Partner, direkte Kommunikation.",
        alt: "Lagergang mit gestapelten, umreiften Wollballen in Uruguay.",
      },
      renvora: {
        kicker: "Renvora",
        title: "Vertriebsarbeit, automatisiert, wo es sinnvoll ist.",
        text: "Renvora verbindet Lead-Recherche, Outreach und Follow-up in einem KI-gestützten Ablauf. Ein Technologie-Venture, derzeit in Entwicklung.",
        alt: "Schematischer Vertriebsablauf vom Lead bis zum Termin.",
      },
    },
    renvoraSteps: ["Lead", "Recherche", "Outreach", "Antwort", "Termin"],
    renvoraCaption: "Schematische Darstellung",
  },
  principles: {
    eyebrow: "Prinzipien",
    title: ["Was unsere Unternehmen", "verbindet."],
    items: [
      { title: "Technologie", text: "Wir setzen Technologie dort ein, wo sie die Arbeitsweise einer traditionellen Branche verändert — und ein Geschäft skalierbar macht." },
      { title: "Umsetzung", text: "Wir bauen und betreiben. Jedes Unternehmen der Gruppe leistet echte Arbeit für echte Kunden." },
      { title: "Internationale Perspektive", text: "Wir verbinden Chancen zwischen Uruguay, Lateinamerika und Märkten in Europa und darüber hinaus." },
      { title: "Langfristiger Wert", text: "Wir bauen Unternehmen auf Dauer: zuerst tragfähige Wirtschaftlichkeit, dann Wachstum." },
    ],
  },
  uruguay: {
    eyebrow: "Herkunft",
    title: ["Aufgebaut in Uruguay.", "Verbunden mit der Welt."],
    text: "Von Uruguay aus arbeitet die Gruppe: ein stabiles Land mit starker Agrarwirtschaft und offenem Zugang zu internationalen Märkten. Von hier aus arbeitet Kunz Global mit Partnern und Kunden in Lateinamerika und Europa.",
    points: [
      { title: "Operativer Standort", text: "San José, Uruguay — nah an den Feldern und am Hafen von Montevideo." },
      { title: "Europäische Wurzeln", text: "Europäischer Hintergrund und enge Verbindungen in den deutschsprachigen Raum." },
      { title: "Vier Sprachen", text: "Englisch, Spanisch, Deutsch und Portugiesisch im Tagesgeschäft." },
    ],
    globeAlt: "Globus mit Blick auf den Südatlantik, Uruguay markiert, Verbindungen nach Europa, Nordamerika und Brasilien.",
    marker: "Uruguay",
  },
  future: {
    eyebrow: "Vision",
    title: ["Wir bauen,", "was als Nächstes kommt."],
    text: "Kunz Global prüft und entwickelt laufend neue Ventures — in Branchen, in denen Technologie, sich verändernde Märkte und operative Chancen langfristiges Potenzial schaffen.",
    fields: ["Technologie", "Landwirtschaft", "Energie", "Infrastruktur", "Handel", "Dienstleistungen"],
    note: "Neue Ventures werden vorgestellt, wenn sie operativ sind. Nicht vorher.",
  },
  cta: {
    title: ["Sprechen wir darüber,", "was wir aufbauen können."],
    text: "Für Partnerschaften, geschäftliche Anfragen oder Fragen zu einem unserer Unternehmen.",
    button: "Kontakt aufnehmen",
  },
  businessesPage: {
    eyebrow: "Portfolio",
    title: ["Sechs Unternehmen.", "Eine Gruppe."],
    lead: "Jedes Unternehmen im Portfolio ist spezialisiert, tritt unter eigener Marke auf und wird innerhalb von Kunz Global betrieben.",
    focusLabel: "Schwerpunkte",
    futureLink: "Was als Nächstes kommt",
  },
  about: {
    eyebrow: "Über Kunz Global",
    title: ["Europäische Wurzeln.", "Aufgebaut in Uruguay."],
    lead: "Kunz Global ist eine Unternehmensgruppe, die spezialisierte Unternehmen entwickelt und betreibt — gegründet und geführt von Stanley Kunz in San José, Uruguay.",
    story: [
      { title: "Wo es begann", text: "Am Anfang standen ein europäischer Hintergrund und die Entscheidung, in Uruguay aufzubauen — einem Land mit starker Landwirtschaft, stabilen Institutionen und Raum für neue Geschäftsmodelle." },
      { title: "Vom Betrieb zur Technologie", text: "Die ersten Unternehmen waren operativ: Agrardienstleistungen im Feld und Handel mit Agrarprodukten. Die Arbeit in diesen Branchen zeigte, wo Software fehlt. Genau daraus ist Agralon entstanden." },
      { title: "Eine Gruppe, mehrere Spezialisten", text: "Vertrieb und Business Development wurden zu eigenen Unternehmen, dazu kamen Versicherung und Vertriebstechnologie. Heute vereint Kunz Global Landwirtschaft, Software, internationalen Handel und Business Services unter einem Dach." },
      { title: "Was als Nächstes kommt", text: "Die Gruppe steht noch am Anfang einer längeren Entwicklung. Neue Ventures kommen hinzu, wenn es eine echte Chance gibt — und die Kapazität, sie gut umzusetzen." },
    ],
    approachTitle: "Wie wir arbeiten",
    leadership: {
      eyebrow: "Führung",
      title: "Stanley Kunz",
      role: "Gründer & Direktor",
      text: "Stanley Kunz führt Kunz Global und steht persönlich für Ausrichtung und Qualität jedes Unternehmens der Gruppe — mit klaren Ansprechpartnern und direkter Kommunikation.",
      photoAlt: "Porträt von Stanley Kunz, Gründer und Direktor von Kunz Global.",
    },
    facts: [
      { label: "Sitz", value: "San José, Uruguay" },
      { label: "Unternehmen", value: "Sechs aktive Marken" },
      { label: "Felder", value: "Landwirtschaft, Software, Handel, Versicherung, Vertrieb" },
    ],
  },
  contactPage: {
    eyebrow: "Kontakt",
    title: ["Beginnen wir ein", "Gespräch."],
    lead: "Schreiben Sie uns kurz, worum es geht. Wir leiten Ihre Nachricht an das richtige Unternehmen weiter und antworten persönlich.",
    form: {
      name: "Name",
      company: "Unternehmen",
      email: "E-Mail",
      area: "Interessensbereich",
      areaGeneral: "Allgemein / Partnerschaften",
      message: "Nachricht",
      optional: "optional",
      submit: "E-Mail vorbereiten",
      note: "Dieses Formular öffnet Ihr E-Mail-Programm mit der vorbereiteten Nachricht. Diese Website sendet und speichert nichts.",
      success: "Ihr E-Mail-Programm sollte jetzt geöffnet sein. Falls nicht, schreiben Sie uns bitte direkt an",
      errorRequired: "Bitte füllen Sie dieses Feld aus.",
      errorEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
      mailSubject: "Anfrage über kunzglobal.com",
    },
    directTitle: "Direkter Kontakt",
    emailLabel: "E-Mail",
    phoneLabel: "Telefon",
    locationLabel: "Standort",
    location: "San José, Uruguay",
  },
  footer: {
    tagline: "Eine Gruppe. Mehrere Unternehmen. Eine Vision.",
    businesses: "Unternehmen",
    company: "Gruppe",
    legalTitle: "Rechtliches",
    legal: "Impressum",
    privacy: "Datenschutz",
    terms: "AGB",
    location: "San José, Uruguay",
    rights: "Alle Rechte vorbehalten.",
  },
  notFound: {
    title: "Diese Seite gibt es nicht.",
    text: "Möglicherweise hat sich die Adresse mit dem Relaunch von kunzglobal.com geändert.",
    back: "Zur Startseite",
  },
  legalOverrides: {
    brandsTitle: "Unternehmen und externe Websites",
    brandsText:
      "Diese Website informiert über die Unternehmen von Kunz Global. Die folgenden Websites werden eigenständig betrieben; für ihre Inhalte gelten die jeweiligen dortigen Impressen:",
    socialTitle: "Telefon und WhatsApp",
    socialText:
      "Wenn Sie uns per Telefon oder WhatsApp kontaktieren, gelten zusätzlich die Datenschutzbestimmungen des jeweiligen Anbieters (für WhatsApp: Meta Platforms, Inc.). Auf die dortige Datenverarbeitung durch den Anbieter haben wir keinen Einfluss.",
    formTitle: "Kontaktformular",
    formText:
      "Das Kontaktformular dieser Website übermittelt keine Daten an uns oder an Dritte. Es bereitet lediglich eine Nachricht in Ihrem eigenen E-Mail-Programm vor; versendet wird sie erst, wenn Sie sie dort absenden. Diese Website setzt keine Cookies, lädt ihre Schriften vom eigenen Server und verwendet keine Analysewerkzeuge.",
    updated: "Stand: September 2026",
  },
};
