import type { Content } from "./types";

export const en: Content = {
  meta: {
    home: {
      title: "Kunz Global — One Group. Multiple Businesses. One Vision.",
      description:
        "Kunz Global is a business group that builds and operates specialised companies across agriculture, technology, international trade and business services. Based in Uruguay, working internationally.",
    },
    businesses: {
      title: "Our Businesses — Kunz Global",
      description:
        "The Kunz Global portfolio: Kunz Agrotech, Agralon, Kunz Sourcing, Renvora, Kunz Systems, KunzAkquise and Vomando — independent brands, one connected group.",
    },
    about: {
      title: "About — Kunz Global",
      description:
        "European roots, built in Uruguay. How Kunz Global develops specialised businesses across agriculture, software, trade and services — and why they belong together.",
    },
    contact: {
      title: "Contact — Kunz Global",
      description: "Get in touch with Kunz Global for partnerships, business enquiries or questions about one of our businesses.",
    },
    legal: { title: "Legal Notice — Kunz Global", description: "Legal notice and provider information for kunzglobal.com." },
    privacy: { title: "Privacy Policy — Kunz Global", description: "How kunzglobal.com handles personal data." },
    terms: { title: "Terms and Conditions — Kunz Global", description: "General terms and conditions of Kunz Global." },
    notFound: { title: "Page not found — Kunz Global", description: "The requested page does not exist." },
  },
  nav: {
    businesses: "Businesses",
    about: "About",
    vision: "Vision",
    contact: "Contact",
    menu: "Menu",
    close: "Close",
    language: "Language",
    skip: "Skip to content",
    home: "Kunz Global — home",
  },
  hero: {
    eyebrow: "Business Group · Uruguay",
    title: ["One group. Multiple businesses.", "One vision."],
    lead: "Kunz Global develops and operates specialised businesses across agriculture, technology, international trade and business services.",
    ctaPrimary: "Explore our businesses",
    ctaSecondary: "About Kunz Global",
    sectors: ["Agriculture", "Software", "International Trade", "Sales Technology", "Language Technology", "Business Services"],
    networkAlt: "Abstract network: Kunz Global at the centre, connected to its business areas.",
    scroll: "Scroll",
  },
  group: {
    eyebrow: "The Group",
    title: ["A platform for building", "specialised companies."],
    lead: "Kunz Global identifies opportunities, develops business models and builds the companies that pursue them.",
    body: "Each business has its own brand, its own market and its own focus. The group connects them — with shared technology, operational experience and an international outlook.",
    facts: [
      { label: "Base", value: "San José, Uruguay" },
      { label: "Portfolio", value: "Seven active businesses" },
      { label: "Sectors", value: "Agriculture · Technology · Trade · Sales" },
      { label: "Working languages", value: "English · Español · Deutsch · Português" },
    ],
  },
  portfolio: {
    eyebrow: "Portfolio",
    title: ["Our", "businesses."],
    lead: "Seven brands, each specialised in its field. Built, owned and operated within the group.",
    viewAll: "All businesses in detail",
    external: "opens in a new tab",
    siteLang: { en: "site in English", es: "site in Spanish", de: "site in German", pt: "site in Portuguese" },
    agralonFlow: ["Enquiry", "Scheduling", "Field work", "Report", "Invoice"],
    sampleData: "Product view with sample data",
    renvoraFlow: ["Research", "Outreach", "Follow-up"],
    illustration: "Illustration",
    systemsModules: ["Web platforms", "Mobile apps", "Automation", "AI workflows"],
    systemsCaption: "Schematic view",
    akquiseSteps: ["Target list", "First contact", "Appointment"],
    akquiseCaption: "Service process",
    vomando: { course: "Spanish · Uruguay", lesson: "Everyday phrases", neutral: "Neutral", local: "Uruguay", meaning: "Can you give me a hand?", caption: "Schematic app view" },
  },
  businesses: {
    agrotech: {
      category: "Agricultural Technology",
      short: "Agricultural drone operations and precision application services for producers in Uruguay.",
      offer: "Drone application for farms in Uruguay: crop protection, broadcast seeding and solid fertiliser from the air, including fields that are hard to reach with ground machinery.",
      cta: "View drone services",
      long: "Kunz Agrotech is the group's agricultural drone service. With a DJI Agras T100 it sprays crop protection products, broadcasts seed and spreads solid fertiliser for farms in Uruguay, including low-lying or wet areas where ground machinery struggles. Each job is set up for its crop, product and field conditions and planned together with producers and their agronomists.",
      focus: ["Crop protection spraying", "Broadcast seeding", "Solid fertiliser", "Hard-to-reach areas"],
    },
    agralon: {
      category: "Agricultural Software",
      short: "The operating platform for agricultural service providers and drone operators — from the first enquiry to the invoice.",
      offer: "Software for agricultural service companies and drone operators: one workflow from the customer's enquiry through scheduling and field work to report and invoice.",
      cta: "Discover Agralon",
      long: "Agralon brings the daily work of agricultural service companies into one system: enquiries, customers and fields, scheduling of pilots and machines with a weather check, the pilot app for field work (also without signal), application reports, quotes, invoices and payments. It grew out of Kunz Agrotech's own drone operations and works independently of the drone brand.",
      focus: ["Enquiries & jobs", "Customers & fields", "Scheduling & weather", "Pilot app", "Reports", "Quotes & invoices"],
      status: "Early access open",
    },
    sourcing: {
      category: "International Trade & Sourcing",
      short: "Uruguayan beef and Merino wool for international B2B buyers, sourced at origin and handled as structured trade.",
      offer: "Pasture-raised, grass-fed beef from Uruguay for importers, wholesalers and processors, sourced through EU-approved export plants. Complemented by Merino wool.",
      cta: "View sourcing offer",
      long: "Kunz Sourcing is the group's trading business and the buyer's counterpart in Uruguay. Its focus is beef: premium cuts, processing cuts and industrial beef, chilled or frozen, sourced to specification through EU-approved Uruguayan export plants; plant, specification and documentation are confirmed before a quote. Merino wool complements the range: combed tops and scoured wool, produced to order at an established Uruguayan combing mill.",
      focus: ["Grass-fed beef", "Premium & processing cuts", "Merino wool", "Export from Uruguay"],
    },
    renvora: {
      category: "Sales Technology",
      short: "Software for lead generation, outreach and sales automation — AI applied to the repetitive work in B2B sales.",
      offer: "Software for B2B sales teams: it researches suitable companies, drafts the first message and keeps follow-ups going. Your team decides how much runs automatically.",
      cta: "Get to know Renvora",
      long: "Renvora is the group's sales software. It learns what a company sells and to whom, finds and ranks matching prospects, writes the outreach and keeps follow-ups going, while the team decides how much runs on its own. Renvora is in development, is used for the group's own brands first and opens to a small number of B2B companies through early access.",
      focus: ["Prospect research", "Outreach", "Follow-ups", "Sales pipeline"],
      status: "In development · early access",
    },
    systems: {
      category: "Software, Apps & Automation",
      short: "Custom software, web platforms, mobile apps and automation for businesses, and the technology behind the group's own products.",
      offer: "Custom software, web platforms, mobile apps and process automation, including AI-supported workflows. Built around how a business actually operates.",
      cta: "Discuss a project",
      long: "Kunz Systems is the group's software and digital engineering business. It designs and builds custom software, web platforms, mobile apps, company websites and internal business tools, and automates recurring processes, including AI-supported workflows. The group's own products, among them Agralon and Renvora, are built by Kunz Systems. Its own website is in preparation; enquiries are handled through Kunz Global.",
      focus: ["Custom software", "Web platforms & websites", "Mobile apps", "Process & AI automation", "Internal business tools"],
      status: "Website in preparation",
    },
    akquise: {
      category: "B2B Sales & Business Development",
      short: "Specialised outbound sales for B2B companies: lead generation, cold outreach and appointment setting.",
      offer: "Outbound sales carried out for B2B companies: researching target companies, first contact by phone and email, and arranging appointments. A service, not software.",
      cta: "View sales services",
      long: "KunzAkquise runs outbound sales for B2B companies as a service: defining the target customer profile, researching companies and contacts, first contact by phone after approval, email campaigns with follow-ups, qualification and appointment setting. Results are handed over as the agreed contact details, call notes or appointments. Where Renvora is software a team uses itself, KunzAkquise does the work for the client.",
      focus: ["Lead research", "Cold calling", "Email outreach", "Appointment setting"],
    },
    vomando: {
      category: "Language Learning Technology",
      short: "A mobile app for learning a language the way it is spoken in a specific country. First course: Spanish as spoken in Uruguay.",
      offer: "A mobile app for learning a language the way it is actually spoken in a specific country: structured lessons, speaking practice and regional usage. First course: Spanish · Uruguay.",
      cta: "Enquire via Kunz Global",
      long: "Vomando is the group's consumer technology product for language learning. It teaches not only what is grammatically correct, but what sounds natural and what is common locally, from neutral to casual. The first course is Spanish as spoken in Uruguay; further languages and regional variants are planned. The app is designed for structured lessons, speaking practice and AI-supported conversation, and is currently in development.",
      focus: ["Mobile app", "Structured lessons", "Speaking practice", "Regional language"],
      status: "In development",
    },
  },
  ecosystem: {
    eyebrow: "Ecosystem",
    title: ["Independent brands.", "One connected group."],
    lead: "What one business learns, the others can use. Field operations shape the software. Sales expertise opens markets. Trade connects Uruguay with buyers abroad.",
    centerLabel: "The Group",
    centerText: "Kunz Global sets direction, provides shared technology and experience, and develops new ventures.",
    futureName: "Future Ventures",
    futureCategory: "In development",
    futureText: "New businesses are evaluated and built continuously. They appear here once they are ready.",
  },
  featured: {
    eyebrow: "Featured ventures",
    title: ["Substance,", "business by business."],
    items: {
      agrotech: {
        kicker: "Kunz Agrotech",
        title: "A working day in the field.",
        text: "A DJI Agras T100 on a harvested field, with support vehicle, water tank and mixing trailer. Each job is set up for its crop, product and field conditions, and the coverage is checked with water-sensitive cards.",
        alt: "Kunz Agrotech's DJI Agras T100 on a harvested field in Uruguay, with the support vehicle and a trailer with water tank and mixing equipment.",
      },
      agralon: {
        kicker: "Agralon",
        title: "From the enquiry to the payment.",
        text: "Every job moves through the same stages. The office plans, the pilot works from the app, and report and invoice are built from the job data.",
        alt: "Agralon with sample data: dashboard with today's jobs, weather and field map on a laptop, and the pilot app on a phone.",
      },
      sourcing: {
        kicker: "Kunz Sourcing",
        title: "Beef and Merino wool from Uruguay.",
        text: "Kunz Sourcing sources beef to the buyer's specification through EU-approved Uruguayan export plants, and Merino wool as combed tops and scoured wool produced to order. Specification, documentation and shipment are coordinated from Uruguay.",
        alt: "Illustration: cattle on pasture in Uruguay; inset photo: combed wool tops at a Uruguayan combing mill.",
      },
      renvora: {
        kicker: "Renvora",
        title: "Prospecting, outreach and follow-up in one loop.",
        text: "Renvora finds companies that fit, writes the first message, keeps the conversation going and brings meetings into the pipeline. The product is in development; early access is open to a small number of B2B companies.",
        alt: "Schematic sales workflow from research to meeting.",
      },
    },
    renvoraSteps: ["Research", "Qualify", "Outreach", "Follow-up", "Meeting"],
    renvoraCaption: "Schematic illustration",
    agralonSteps: ["Enquiry", "Coordination", "Scheduling", "Field work", "Report", "Invoice", "Payment"],
    agralonStepsLabel: "The Agralon workflow",
    sourcingFacts: [
      { term: "Beef", value: "Premium, processing and industrial cuts · chilled or frozen" },
      { term: "Supply", value: "EU-approved Uruguayan export plants" },
      { term: "Merino wool", value: "Wool tops · scoured wool, produced to order" },
    ],
    statusLabel: "Status",
  },
  principles: {
    eyebrow: "Principles",
    title: ["What connects", "our businesses."],
    items: [
      { title: "Technology", text: "We use technology where it changes how a traditional industry works — and makes a business scalable." },
      { title: "Execution", text: "We build and operate. Every business in the group does real work for real customers." },
      { title: "International perspective", text: "We connect opportunities between Uruguay, Latin America and markets in Europe and beyond." },
      { title: "Long-term value", text: "We build companies to last: sound economics first, growth second." },
    ],
  },
  uruguay: {
    eyebrow: "Origin",
    title: ["Built in Uruguay.", "Connected to the world."],
    text: "Uruguay is where the group operates from: a stable country with a strong agricultural base and open access to international markets. From here, Kunz Global works with partners and customers in Latin America and Europe.",
    points: [
      { title: "Operating base", text: "San José, Uruguay — close to the fields and to the port of Montevideo." },
      { title: "European roots", text: "A European background and close ties to German-speaking markets." },
      { title: "Four languages", text: "English, Spanish, German and Portuguese in daily business." },
    ],
    globeAlt: "Globe centred on the South Atlantic with Uruguay marked and connections towards Europe, North America and Brazil.",
    marker: "Uruguay",
  },
  future: {
    eyebrow: "Vision",
    title: ["Building what", "comes next."],
    text: "Kunz Global continuously evaluates and develops new ventures — in industries where technology, changing markets and operational opportunity create long-term potential.",
    fields: ["Technology", "Agriculture", "Energy", "Infrastructure", "Trade", "Services"],
    note: "New ventures are announced when they are operational. Not before.",
  },
  cta: {
    title: ["Let's talk about", "what we can build."],
    text: "For partnerships, business enquiries or questions about one of our businesses.",
    button: "Contact Kunz Global",
  },
  businessesPage: {
    eyebrow: "Portfolio",
    title: ["Seven businesses.", "One group."],
    lead: "Each company in the portfolio is specialised, independently branded and operated within Kunz Global.",
    focusLabel: "Focus",
    futureLink: "See what comes next",
  },
  about: {
    eyebrow: "About Kunz Global",
    title: ["European roots.", "Built in Uruguay."],
    lead: "Kunz Global is a business group that develops and operates specialised companies — founded and led by Stanley Kunz from San José, Uruguay.",
    story: [
      { title: "Where it started", text: "Kunz Global began with a European background and a decision to build in Uruguay — a country with strong agriculture, stable institutions and room for new business models." },
      { title: "From operations to technology", text: "The first businesses were operational: agricultural services in the field and trade in agricultural products. Working in these industries showed where software was missing. Agralon grew out of exactly that." },
      { title: "One group, several specialists", text: "Sales and business development became businesses of their own, followed by sales technology, software engineering and language-learning technology. Today Kunz Global combines agriculture, software, international trade and business services under one roof." },
      { title: "What comes next", text: "The group is still at the beginning of a longer development. New ventures are added when there is a real opportunity and the capacity to execute it well." },
    ],
    approachTitle: "How we work",
    leadership: {
      eyebrow: "Leadership",
      title: "Stanley Kunz",
      role: "Founder & Director",
      text: "Stanley Kunz leads Kunz Global and is personally responsible for the direction and quality of every business in the group — with clear points of contact and direct communication.",
      photoAlt: "Portrait of Stanley Kunz, Founder and Director of Kunz Global.",
    },
    facts: [
      { label: "Registered office", value: "San José, Uruguay" },
      { label: "Businesses", value: "Seven active brands" },
      { label: "Fields", value: "Agriculture, software, trade, sales" },
    ],
  },
  contactPage: {
    eyebrow: "Contact",
    title: ["Start a", "conversation."],
    lead: "Tell us briefly what it is about. We will route your message to the right business and reply personally.",
    form: {
      name: "Name",
      company: "Company",
      email: "Email",
      area: "Area of interest",
      areaGeneral: "General / Partnerships",
      message: "Message",
      optional: "optional",
      submit: "Prepare email",
      note: "This form opens your email program with your message prepared. Nothing is sent or stored by this website.",
      success: "Your email program should now be open. If not, please write to us directly at",
      errorRequired: "Please fill in this field.",
      errorEmail: "Please enter a valid email address.",
      mailSubject: "Enquiry via kunzglobal.com",
    },
    directTitle: "Direct contact",
    emailLabel: "Email",
    phoneLabel: "Phone",
    locationLabel: "Location",
    location: "San José, Uruguay",
  },
  footer: {
    tagline: "One group. Multiple businesses. One vision.",
    businesses: "Businesses",
    company: "Group",
    legalTitle: "Legal",
    legal: "Legal notice",
    privacy: "Privacy",
    terms: "Terms",
    location: "San José, Uruguay",
    rights: "All rights reserved.",
  },
  notFound: {
    title: "This page does not exist.",
    text: "The address may have changed with the relaunch of kunzglobal.com.",
    back: "Back to the homepage",
  },
  legalOverrides: {
    brandsTitle: "Businesses and external websites",
    brandsText:
      "This website provides information about the businesses of Kunz Global. The following websites are operated separately; their own legal notices apply to their content:",
    socialTitle: "Phone and WhatsApp",
    socialText:
      "If you contact us by phone or WhatsApp, the privacy terms of the respective provider (for WhatsApp: Meta Platforms, Inc.) apply in addition. We have no influence over data processing carried out there by the provider.",
    formTitle: "Contact form",
    formText:
      "The contact form on this website does not transmit any data to us or to third parties. It only prepares a message in your own email program; the message is sent when you send it from there. This website sets no cookies, loads its fonts from its own server and uses no analytics.",
    updated: "Last updated: September 2026",
  },
};
