import type { Content } from "./types";

export const en: Content = {
  meta: {
    home: {
      title: "Kunz Global — One Group. Multiple Businesses. One Vision.",
      description:
        "Kunz Global is a business group that builds and operates specialised companies across agriculture, technology, international trade and business services. Based in Uruguay, working internationally.",
    },
    businesses: {
      title: "Our Businesses — Kunz Global",
      description:
        "The Kunz Global portfolio: Kunz Agrotech, Agralon, Kunz Sourcing, Renvora, Kunz Versicherung and KunzAkquise — independent brands, one connected group.",
    },
    about: {
      title: "About — Kunz Global",
      description:
        "European roots, built in Uruguay. How Kunz Global develops specialised businesses across agriculture, software, trade and services — and why they belong together.",
    },
    contact: {
      title: "Contact — Kunz Global",
      description: "Get in touch with Kunz Global for partnerships, business enquiries or questions about one of our businesses.",
    },
    legal: { title: "Legal Notice — Kunz Global", description: "Legal notice and provider information for kunzglobal.com." },
    privacy: { title: "Privacy Policy — Kunz Global", description: "How kunzglobal.com handles personal data." },
    terms: { title: "Terms and Conditions — Kunz Global", description: "General terms and conditions of Kunz Global." },
    notFound: { title: "Page not found — Kunz Global", description: "The requested page does not exist." },
  },
  nav: {
    businesses: "Businesses",
    about: "About",
    vision: "Vision",
    contact: "Contact",
    menu: "Menu",
    close: "Close",
    language: "Language",
    skip: "Skip to content",
    home: "Kunz Global — home",
  },
  hero: {
    eyebrow: "Business Group · Uruguay",
    title: ["One group. Multiple businesses.", "One vision."],
    lead: "Kunz Global develops and operates specialised businesses across agriculture, technology, international trade and business services.",
    ctaPrimary: "Explore our businesses",
    ctaSecondary: "About Kunz Global",
    sectors: ["Agriculture", "Software", "International Trade", "Sales Technology", "Insurance", "Business Services"],
    networkAlt: "Abstract network: Kunz Global at the centre, connected to its business areas.",
    scroll: "Scroll",
  },
  group: {
    eyebrow: "The Group",
    title: ["A platform for building", "specialised companies."],
    lead: "Kunz Global identifies opportunities, develops business models and builds the companies that pursue them.",
    body: "Each business has its own brand, its own market and its own focus. The group connects them — with shared technology, operational experience and an international outlook.",
    facts: [
      { label: "Base", value: "San José, Uruguay" },
      { label: "Portfolio", value: "Six active businesses" },
      { label: "Sectors", value: "Agriculture · Technology · Trade · Insurance · Sales" },
      { label: "Working languages", value: "English · Español · Deutsch · Português" },
    ],
  },
  portfolio: {
    eyebrow: "Portfolio",
    title: ["Our", "businesses."],
    lead: "Six brands, each specialised in its field. Built, owned and operated within the group.",
    visit: "Visit website",
    noSite: "Enquiries via Kunz Global",
    viewAll: "All businesses in detail",
    external: "opens in a new tab",
  },
  businesses: {
    agrotech: {
      category: "Agricultural Technology",
      short: "Agricultural drone operations and precision application services for producers in Uruguay.",
      long: "Kunz Agrotech is the group's operating agricultural technology business. It applies crop inputs with agricultural drones — precisely, documented, and in close coordination with producers and their agronomists.",
      focus: ["Drone application", "Precision agriculture", "Field services", "Agricultural technology"],
    },
    agralon: {
      category: "Software Platform",
      short: "The operating platform for agricultural service providers and drone operators — from the first enquiry to the invoice.",
      long: "Agralon brings the daily work of agricultural service providers into one system: jobs, customers and fields, weather, fleet and maintenance, operation reports, quotes and invoices. It was built out of real drone operations and works in the field, including offline.",
      focus: ["Operations & jobs", "Customers & fields", "Weather", "Fleet & maintenance", "Reports", "Quotes & invoices"],
    },
    sourcing: {
      category: "International Trade & Sourcing",
      short: "Connects suppliers in Uruguay with international buyers. Current focus: wool and agricultural commodities.",
      long: "Kunz Sourcing is the group's trading business. It sources agricultural products in Uruguay for international B2B buyers and coordinates the path from supplier to shipment. Wool is the current core; further product areas are being developed.",
      focus: ["Wool", "Agricultural commodities", "Export from Uruguay", "B2B trade"],
    },
    renvora: {
      category: "Sales Technology",
      short: "Software for lead generation, outreach and sales automation — AI applied to the repetitive work in B2B sales.",
      long: "Renvora is a software venture in sales technology. It supports lead generation, outreach, CRM-related processes and marketing automation with AI, so that sales teams spend their time on conversations rather than routine.",
      focus: ["Lead generation", "Outreach", "Sales automation", "CRM workflows"],
      status: "In development · early access",
    },
    versicherung: {
      category: "Insurance & Risk Solutions",
      short: "The insurance business within the Kunz ecosystem — built on trust, continuity and long-term client relationships.",
      long: "Kunz Versicherung covers insurance and risk solutions within the Kunz ecosystem. It is a business that rests on trust and continuity, and is run with exactly that in mind.",
      focus: ["Insurance", "Risk solutions"],
    },
    akquise: {
      category: "B2B Sales & Business Development",
      short: "Specialised outbound sales for B2B companies: lead generation, cold outreach and appointment setting.",
      long: "KunzAkquise is the group's business development service. It takes on B2B outbound sales for companies that want new customers without building a sales development team first: research, cold outreach, qualification and appointment setting.",
      focus: ["B2B cold outreach", "Lead generation", "Appointment setting", "Sales development"],
    },
  },
  ecosystem: {
    eyebrow: "Ecosystem",
    title: ["Independent brands.", "One connected group."],
    lead: "What one business learns, the others can use. Field operations shape the software. Sales expertise opens markets. Trade connects Uruguay with buyers abroad.",
    centerLabel: "The Group",
    centerText: "Kunz Global sets direction, provides shared technology and experience, and develops new ventures.",
    futureName: "Future Ventures",
    futureCategory: "In development",
    futureText: "New businesses are evaluated and built continuously. They appear here once they are ready.",
  },
  featured: {
    eyebrow: "Featured ventures",
    title: ["Substance,", "business by business."],
    items: {
      agrotech: {
        kicker: "Kunz Agrotech",
        title: "Precision agriculture, operated in the field.",
        text: "Agricultural drones, application technology and the logistics around them. Kunz Agrotech does the work on the ground — and that experience informs everything else the group builds for agriculture.",
        alt: "Agricultural drone on a harvested field in Uruguay, with the Kunz Agrotech support vehicle and mixing trailer behind it.",
      },
      agralon: {
        kicker: "Agralon",
        title: "One system for the whole operation.",
        text: "Jobs, fields, weather, fleet, reports and invoicing in a single workflow — on the desktop in the office and on the phone in the field. Agralon is a core technology product of the group.",
        alt: "Agralon software: dashboard with jobs, weather and field map on a laptop, and the pilot app on a phone.",
      },
      sourcing: {
        kicker: "Kunz Sourcing",
        title: "From Uruguay to international buyers.",
        text: "Wool and agricultural commodities, sourced at origin and handled as structured B2B trade. Clear specifications, reliable partners, direct communication.",
        alt: "Warehouse aisle with stacked, strapped wool bales in Uruguay.",
      },
      renvora: {
        kicker: "Renvora",
        title: "Sales work, automated where it makes sense.",
        text: "Renvora combines lead research, outreach and follow-up into one AI-supported workflow. A technology venture, currently in development.",
        alt: "Schematic sales workflow from lead to meeting.",
      },
    },
    renvoraSteps: ["Lead", "Research", "Outreach", "Reply", "Meeting"],
    renvoraCaption: "Schematic illustration",
  },
  principles: {
    eyebrow: "Principles",
    title: ["What connects", "our businesses."],
    items: [
      { title: "Technology", text: "We use technology where it changes how a traditional industry works — and makes a business scalable." },
      { title: "Execution", text: "We build and operate. Every business in the group does real work for real customers." },
      { title: "International perspective", text: "We connect opportunities between Uruguay, Latin America and markets in Europe and beyond." },
      { title: "Long-term value", text: "We build companies to last: sound economics first, growth second." },
    ],
  },
  uruguay: {
    eyebrow: "Origin",
    title: ["Built in Uruguay.", "Connected to the world."],
    text: "Uruguay is where the group operates from: a stable country with a strong agricultural base and open access to international markets. From here, Kunz Global works with partners and customers in Latin America and Europe.",
    points: [
      { title: "Operating base", text: "San José, Uruguay — close to the fields and to the port of Montevideo." },
      { title: "European roots", text: "A European background and close ties to German-speaking markets." },
      { title: "Four languages", text: "English, Spanish, German and Portuguese in daily business." },
    ],
    globeAlt: "Globe centred on the South Atlantic with Uruguay marked and connections towards Europe, North America and Brazil.",
    marker: "Uruguay",
  },
  future: {
    eyebrow: "Vision",
    title: ["Building what", "comes next."],
    text: "Kunz Global continuously evaluates and develops new ventures — in industries where technology, changing markets and operational opportunity create long-term potential.",
    fields: ["Technology", "Agriculture", "Energy", "Infrastructure", "Trade", "Services"],
    note: "New ventures are announced when they are operational. Not before.",
  },
  cta: {
    title: ["Let's talk about", "what we can build."],
    text: "For partnerships, business enquiries or questions about one of our businesses.",
    button: "Contact Kunz Global",
  },
  businessesPage: {
    eyebrow: "Portfolio",
    title: ["Six businesses.", "One group."],
    lead: "Each company in the portfolio is specialised, independently branded and operated within Kunz Global.",
    focusLabel: "Focus",
    futureLink: "See what comes next",
  },
  about: {
    eyebrow: "About Kunz Global",
    title: ["European roots.", "Built in Uruguay."],
    lead: "Kunz Global is a business group that develops and operates specialised companies — founded and led by Stanley Kunz from San José, Uruguay.",
    story: [
      { title: "Where it started", text: "Kunz Global began with a European background and a decision to build in Uruguay — a country with strong agriculture, stable institutions and room for new business models." },
      { title: "From operations to technology", text: "The first businesses were operational: agricultural services in the field and trade in agricultural products. Working in these industries showed where software was missing. Agralon grew out of exactly that." },
      { title: "One group, several specialists", text: "Sales and business development became businesses of their own, alongside insurance and sales technology. Today Kunz Global combines agriculture, software, international trade and business services under one roof." },
      { title: "What comes next", text: "The group is still at the beginning of a longer development. New ventures are added when there is a real opportunity and the capacity to execute it well." },
    ],
    approachTitle: "How we work",
    leadership: {
      eyebrow: "Leadership",
      title: "Stanley Kunz",
      role: "Founder & Director",
      text: "Stanley Kunz leads Kunz Global and is personally responsible for the direction and quality of every business in the group — with clear points of contact and direct communication.",
      photoAlt: "Portrait of Stanley Kunz, Founder and Director of Kunz Global.",
    },
    facts: [
      { label: "Registered office", value: "San José, Uruguay" },
      { label: "Businesses", value: "Six active brands" },
      { label: "Fields", value: "Agriculture, software, trade, insurance, sales" },
    ],
  },
  contactPage: {
    eyebrow: "Contact",
    title: ["Start a", "conversation."],
    lead: "Tell us briefly what it is about. We will route your message to the right business and reply personally.",
    form: {
      name: "Name",
      company: "Company",
      email: "Email",
      area: "Area of interest",
      areaGeneral: "General / Partnerships",
      message: "Message",
      optional: "optional",
      submit: "Prepare email",
      note: "This form opens your email program with your message prepared. Nothing is sent or stored by this website.",
      success: "Your email program should now be open. If not, please write to us directly at",
      errorRequired: "Please fill in this field.",
      errorEmail: "Please enter a valid email address.",
      mailSubject: "Enquiry via kunzglobal.com",
    },
    directTitle: "Direct contact",
    emailLabel: "Email",
    phoneLabel: "Phone",
    locationLabel: "Location",
    location: "San José, Uruguay",
  },
  footer: {
    tagline: "One group. Multiple businesses. One vision.",
    businesses: "Businesses",
    company: "Group",
    legalTitle: "Legal",
    legal: "Legal notice",
    privacy: "Privacy",
    terms: "Terms",
    location: "San José, Uruguay",
    rights: "All rights reserved.",
  },
  notFound: {
    title: "This page does not exist.",
    text: "The address may have changed with the relaunch of kunzglobal.com.",
    back: "Back to the homepage",
  },
  legalOverrides: {
    brandsTitle: "Businesses and external websites",
    brandsText:
      "This website provides information about the businesses of Kunz Global. The following websites are operated separately; their own legal notices apply to their content:",
    socialTitle: "Phone and WhatsApp",
    socialText:
      "If you contact us by phone or WhatsApp, the privacy terms of the respective provider (for WhatsApp: Meta Platforms, Inc.) apply in addition. We have no influence over data processing carried out there by the provider.",
    formTitle: "Contact form",
    formText:
      "The contact form on this website does not transmit any data to us or to third parties. It only prepares a message in your own email program; the message is sent when you send it from there. This website sets no cookies, loads its fonts from its own server and uses no analytics.",
    updated: "Last updated: September 2026",
  },
};
