import type { Content } from "./types";

export const es: Content = {
  meta: {
    home: {
      title: "Kunz Global — Un grupo. Varias empresas. Una visión.",
      description:
        "Kunz Global es un grupo empresarial que desarrolla y opera empresas especializadas en agricultura, tecnología, comercio internacional y servicios para empresas. Con base en Uruguay y trabajo internacional.",
    },
    businesses: {
      title: "Nuestras empresas — Kunz Global",
      description:
        "El portafolio de Kunz Global: Kunz Agrotech, Agralon, Kunz Sourcing, Renvora, Kunz Versicherung y KunzAkquise — marcas independientes, un grupo conectado.",
    },
    about: {
      title: "Sobre nosotros — Kunz Global",
      description:
        "Raíces europeas, construido en Uruguay. Cómo Kunz Global desarrolla empresas especializadas en agricultura, software, comercio y servicios — y por qué van juntas.",
    },
    contact: {
      title: "Contacto — Kunz Global",
      description: "Póngase en contacto con Kunz Global por alianzas, consultas comerciales o preguntas sobre una de nuestras empresas.",
    },
    legal: { title: "Aviso legal — Kunz Global", description: "Aviso legal e información del titular de kunzglobal.com." },
    privacy: { title: "Política de privacidad — Kunz Global", description: "Cómo trata kunzglobal.com los datos personales." },
    terms: { title: "Términos y condiciones — Kunz Global", description: "Términos y condiciones generales de Kunz Global." },
    notFound: { title: "Página no encontrada — Kunz Global", description: "La página solicitada no existe." },
  },
  nav: {
    businesses: "Empresas",
    about: "Nosotros",
    vision: "Visión",
    contact: "Contacto",
    menu: "Menú",
    close: "Cerrar",
    language: "Idioma",
    skip: "Saltar al contenido",
    home: "Kunz Global — inicio",
  },
  hero: {
    eyebrow: "Grupo empresarial · Uruguay",
    title: ["Un grupo. Varias empresas.", "Una visión."],
    lead: "Kunz Global desarrolla y opera empresas especializadas en agricultura, tecnología, comercio internacional y servicios para empresas.",
    ctaPrimary: "Conocer nuestras empresas",
    ctaSecondary: "Sobre Kunz Global",
    sectors: ["Agricultura", "Software", "Comercio internacional", "Tecnología de ventas", "Seguros", "Servicios para empresas"],
    networkAlt: "Red abstracta: Kunz Global en el centro, conectado con sus áreas de negocio.",
    scroll: "Desplazar",
  },
  group: {
    eyebrow: "El grupo",
    title: ["Una plataforma para construir", "empresas especializadas."],
    lead: "Kunz Global identifica oportunidades, desarrolla modelos de negocio y construye las empresas que los llevan adelante.",
    body: "Cada empresa tiene su propia marca, su propio mercado y su propio foco. El grupo las conecta — con tecnología compartida, experiencia operativa y una mirada internacional.",
    facts: [
      { label: "Base", value: "San José, Uruguay" },
      { label: "Portafolio", value: "Seis empresas activas" },
      { label: "Sectores", value: "Agricultura · Tecnología · Comercio · Seguros · Ventas" },
      { label: "Idiomas de trabajo", value: "English · Español · Deutsch · Português" },
    ],
  },
  portfolio: {
    eyebrow: "Portafolio",
    title: ["Nuestras", "empresas."],
    lead: "Seis marcas, cada una especializada en su área. Construidas y operadas dentro del grupo.",
    visit: "Visitar sitio web",
    noSite: "Consultas a través de Kunz Global",
    viewAll: "Todas las empresas en detalle",
    external: "se abre en una pestaña nueva",
  },
  businesses: {
    agrotech: {
      category: "Tecnología agrícola",
      short: "Operación de drones agrícolas y servicios de aplicación de precisión para productores en Uruguay.",
      long: "Kunz Agrotech es la empresa operativa de tecnología agrícola del grupo. Aplica insumos con drones agrícolas — con precisión, con registro de cada trabajo y en coordinación con los productores y sus ingenieros agrónomos.",
      focus: ["Aplicación con drones", "Agricultura de precisión", "Servicios en campo", "Tecnología agrícola"],
    },
    agralon: {
      category: "Plataforma de software",
      short: "La plataforma operativa para prestadores de servicios agrícolas y operadores de drones — de la primera consulta a la factura.",
      long: "Agralon reúne el trabajo diario de los prestadores de servicios agrícolas en un solo sistema: trabajos, clientes y campos, clima, flota y mantenimiento, informes de aplicación, presupuestos y facturas. Nació de la operación real con drones y funciona en el campo, también sin conexión.",
      focus: ["Operaciones y trabajos", "Clientes y campos", "Clima", "Flota y mantenimiento", "Informes", "Presupuestos y facturas"],
    },
    sourcing: {
      category: "Comercio internacional y abastecimiento",
      short: "Conecta proveedores de Uruguay con compradores internacionales. Foco actual: lana y materias primas agrícolas.",
      long: "Kunz Sourcing es la empresa comercial del grupo. Abastece productos agrícolas de Uruguay para compradores B2B internacionales y coordina el camino del proveedor al embarque. La lana es hoy el núcleo; otras áreas de producto están en desarrollo.",
      focus: ["Lana", "Materias primas agrícolas", "Exportación desde Uruguay", "Comercio B2B"],
    },
    renvora: {
      category: "Tecnología de ventas",
      short: "Software para generación de leads, prospección y automatización de ventas — IA aplicada al trabajo repetitivo de la venta B2B.",
      long: "Renvora es un emprendimiento de software en tecnología de ventas. Apoya con IA la generación de leads, la prospección, los procesos cercanos al CRM y la automatización de marketing, para que los equipos comerciales dediquen su tiempo a las conversaciones y no a la rutina.",
      focus: ["Generación de leads", "Prospección", "Automatización de ventas", "Flujos de CRM"],
      status: "En desarrollo · acceso anticipado",
    },
    versicherung: {
      category: "Seguros y soluciones de riesgo",
      short: "El área de seguros dentro del ecosistema Kunz — basada en la confianza, la continuidad y relaciones de largo plazo con los clientes.",
      long: "Kunz Versicherung cubre seguros y soluciones de riesgo dentro del ecosistema Kunz. Es un negocio que se apoya en la confianza y la continuidad, y se gestiona exactamente con ese criterio.",
      focus: ["Seguros", "Soluciones de riesgo"],
    },
    akquise: {
      category: "Ventas B2B y desarrollo de negocios",
      short: "Ventas salientes especializadas para empresas B2B: generación de leads, prospección en frío y agenda de reuniones.",
      long: "KunzAkquise es el servicio de desarrollo de negocios del grupo. Asume la venta saliente B2B para empresas que quieren nuevos clientes sin armar antes un equipo propio: investigación, prospección en frío, calificación y agenda de reuniones.",
      focus: ["Prospección B2B en frío", "Generación de leads", "Agenda de reuniones", "Desarrollo de ventas"],
    },
  },
  ecosystem: {
    eyebrow: "Ecosistema",
    title: ["Marcas independientes.", "Un grupo conectado."],
    lead: "Lo que aprende una empresa lo aprovechan las demás. La operación en campo da forma al software. La experiencia en ventas abre mercados. El comercio conecta Uruguay con compradores en el exterior.",
    centerLabel: "El grupo",
    centerText: "Kunz Global marca el rumbo, aporta tecnología y experiencia compartidas, y desarrolla nuevos emprendimientos.",
    futureName: "Future Ventures",
    futureCategory: "En desarrollo",
    futureText: "Evaluamos y construimos nuevas empresas de forma continua. Aparecen aquí cuando están listas.",
  },
  featured: {
    eyebrow: "Empresas destacadas",
    title: ["Sustancia,", "empresa por empresa."],
    items: {
      agrotech: {
        kicker: "Kunz Agrotech",
        title: "Agricultura de precisión, operada en el campo.",
        text: "Drones agrícolas, tecnología de aplicación y la logística que los rodea. Kunz Agrotech hace el trabajo en el terreno — y esa experiencia alimenta todo lo demás que el grupo construye para el agro.",
        alt: "Dron agrícola sobre un rastrojo en Uruguay, con la camioneta de apoyo de Kunz Agrotech y el tráiler de mezcla detrás.",
      },
      agralon: {
        kicker: "Agralon",
        title: "Un solo sistema para toda la operación.",
        text: "Trabajos, campos, clima, flota, informes y facturación en un único flujo — en el escritorio de la oficina y en el teléfono en el campo. Agralon es un producto tecnológico central del grupo.",
        alt: "Software Agralon: panel con trabajos, clima y mapa del campo en una laptop, y la app del piloto en un teléfono.",
      },
      sourcing: {
        kicker: "Kunz Sourcing",
        title: "De Uruguay a compradores internacionales.",
        text: "Lana y materias primas agrícolas, abastecidas en origen y gestionadas como comercio B2B estructurado. Especificaciones claras, socios confiables, comunicación directa.",
        alt: "Pasillo de un depósito con fardos de lana apilados y zunchados en Uruguay.",
      },
      renvora: {
        kicker: "Renvora",
        title: "El trabajo comercial, automatizado donde tiene sentido.",
        text: "Renvora une la investigación de leads, la prospección y el seguimiento en un flujo apoyado por IA. Un emprendimiento tecnológico, actualmente en desarrollo.",
        alt: "Flujo comercial esquemático, del lead a la reunión.",
      },
    },
    renvoraSteps: ["Lead", "Investigación", "Contacto", "Respuesta", "Reunión"],
    renvoraCaption: "Ilustración esquemática",
  },
  principles: {
    eyebrow: "Principios",
    title: ["Lo que conecta", "a nuestras empresas."],
    items: [
      { title: "Tecnología", text: "Usamos tecnología donde cambia la forma de trabajar de una industria tradicional — y vuelve escalable un negocio." },
      { title: "Ejecución", text: "Construimos y operamos. Cada empresa del grupo hace trabajo real para clientes reales." },
      { title: "Mirada internacional", text: "Conectamos oportunidades entre Uruguay, América Latina y mercados de Europa y más allá." },
      { title: "Valor a largo plazo", text: "Construimos empresas para durar: primero una economía sana, después el crecimiento." },
    ],
  },
  uruguay: {
    eyebrow: "Origen",
    title: ["Construido en Uruguay.", "Conectado con el mundo."],
    text: "Uruguay es el lugar desde donde opera el grupo: un país estable, con una base agropecuaria fuerte y acceso abierto a los mercados internacionales. Desde aquí, Kunz Global trabaja con socios y clientes en América Latina y Europa.",
    points: [
      { title: "Base operativa", text: "San José, Uruguay — cerca del campo y del puerto de Montevideo." },
      { title: "Raíces europeas", text: "Origen europeo y vínculos estrechos con los mercados de habla alemana." },
      { title: "Cuatro idiomas", text: "Inglés, español, alemán y portugués en el trabajo diario." },
    ],
    globeAlt: "Globo centrado en el Atlántico Sur con Uruguay marcado y conexiones hacia Europa, América del Norte y Brasil.",
    marker: "Uruguay",
  },
  future: {
    eyebrow: "Visión",
    title: ["Construimos", "lo que viene."],
    text: "Kunz Global evalúa y desarrolla nuevos emprendimientos de forma continua — en industrias donde la tecnología, los mercados en cambio y las oportunidades operativas crean potencial a largo plazo.",
    fields: ["Tecnología", "Agricultura", "Energía", "Infraestructura", "Comercio", "Servicios"],
    note: "Los nuevos emprendimientos se anuncian cuando están operativos. No antes.",
  },
  cta: {
    title: ["Hablemos de lo que", "podemos construir."],
    text: "Para alianzas, consultas comerciales o preguntas sobre una de nuestras empresas.",
    button: "Contactar a Kunz Global",
  },
  businessesPage: {
    eyebrow: "Portafolio",
    title: ["Seis empresas.", "Un grupo."],
    lead: "Cada empresa del portafolio es especializada, tiene marca propia y se opera dentro de Kunz Global.",
    focusLabel: "Foco",
    futureLink: "Ver lo que viene",
  },
  about: {
    eyebrow: "Sobre Kunz Global",
    title: ["Raíces europeas.", "Construido en Uruguay."],
    lead: "Kunz Global es un grupo empresarial que desarrolla y opera empresas especializadas — fundado y dirigido por Stanley Kunz desde San José, Uruguay.",
    story: [
      { title: "Dónde empezó", text: "Kunz Global nació de un origen europeo y de la decisión de construir en Uruguay — un país con un agro fuerte, instituciones estables y espacio para nuevos modelos de negocio." },
      { title: "De la operación a la tecnología", text: "Las primeras empresas fueron operativas: servicios agrícolas en el campo y comercio de productos agrícolas. Trabajar en esas industrias mostró dónde faltaba software. Agralon surgió exactamente de ahí." },
      { title: "Un grupo, varios especialistas", text: "Las ventas y el desarrollo de negocios se convirtieron en empresas propias, junto con seguros y tecnología de ventas. Hoy Kunz Global reúne agricultura, software, comercio internacional y servicios para empresas bajo un mismo techo." },
      { title: "Lo que viene", text: "El grupo está todavía al comienzo de un desarrollo más largo. Se suman nuevos emprendimientos cuando hay una oportunidad real y la capacidad de ejecutarla bien." },
    ],
    approachTitle: "Cómo trabajamos",
    leadership: {
      eyebrow: "Dirección",
      title: "Stanley Kunz",
      role: "Fundador y Director",
      text: "Stanley Kunz dirige Kunz Global y responde personalmente por el rumbo y la calidad de cada empresa del grupo — con interlocutores claros y comunicación directa.",
      photoAlt: "Retrato de Stanley Kunz, fundador y director de Kunz Global.",
    },
    facts: [
      { label: "Sede", value: "San José, Uruguay" },
      { label: "Empresas", value: "Seis marcas activas" },
      { label: "Áreas", value: "Agricultura, software, comercio, seguros, ventas" },
    ],
  },
  contactPage: {
    eyebrow: "Contacto",
    title: ["Iniciemos una", "conversación."],
    lead: "Cuéntenos brevemente de qué se trata. Derivamos su mensaje a la empresa que corresponde y respondemos personalmente.",
    form: {
      name: "Nombre",
      company: "Empresa",
      email: "Correo electrónico",
      area: "Área de interés",
      areaGeneral: "General / Alianzas",
      message: "Mensaje",
      optional: "opcional",
      submit: "Preparar correo",
      note: "Este formulario abre su programa de correo con el mensaje ya preparado. Este sitio no envía ni guarda ningún dato.",
      success: "Su programa de correo debería estar abierto. Si no es así, escríbanos directamente a",
      errorRequired: "Por favor complete este campo.",
      errorEmail: "Por favor ingrese un correo electrónico válido.",
      mailSubject: "Consulta desde kunzglobal.com",
    },
    directTitle: "Contacto directo",
    emailLabel: "Correo",
    phoneLabel: "Teléfono",
    locationLabel: "Ubicación",
    location: "San José, Uruguay",
  },
  footer: {
    tagline: "Un grupo. Varias empresas. Una visión.",
    businesses: "Empresas",
    company: "Grupo",
    legalTitle: "Legal",
    legal: "Aviso legal",
    privacy: "Privacidad",
    terms: "Términos",
    location: "San José, Uruguay",
    rights: "Todos los derechos reservados.",
  },
  notFound: {
    title: "Esta página no existe.",
    text: "Es posible que la dirección haya cambiado con el relanzamiento de kunzglobal.com.",
    back: "Volver al inicio",
  },
  legalOverrides: {
    brandsTitle: "Empresas y sitios web externos",
    brandsText:
      "Este sitio web informa sobre las empresas de Kunz Global. Los siguientes sitios se operan por separado; para sus contenidos rigen sus propios avisos legales:",
    socialTitle: "Teléfono y WhatsApp",
    socialText:
      "Si nos contacta por teléfono o WhatsApp, rigen además las condiciones de privacidad del proveedor respectivo (para WhatsApp: Meta Platforms, Inc.). No tenemos influencia sobre el tratamiento de datos que realiza dicho proveedor.",
    formTitle: "Formulario de contacto",
    formText:
      "El formulario de contacto de este sitio no transmite datos a nosotros ni a terceros. Solo prepara un mensaje en su propio programa de correo; el mensaje se envía cuando usted lo envía desde allí. Este sitio no instala cookies, carga sus tipografías desde su propio servidor y no usa herramientas de análisis.",
    updated: "Última actualización: septiembre de 2026",
  },
};
