import type { Content } from "./types";

export const es: Content = {
  meta: {
    home: {
      title: "Kunz Global — Un grupo. Varias empresas. Una visión.",
      description:
        "Kunz Global es un grupo empresarial que desarrolla y opera empresas especializadas en agricultura, tecnología, comercio internacional y servicios para empresas. Con base en Uruguay y trabajo internacional.",
    },
    businesses: {
      title: "Nuestras empresas — Kunz Global",
      description:
        "El portafolio de Kunz Global: Kunz Agrotech, Agralon, Kunz Sourcing, Renvora, Kunz Versicherung y KunzAkquise — marcas independientes, un grupo conectado.",
    },
    about: {
      title: "Sobre nosotros — Kunz Global",
      description:
        "Raíces europeas, construido en Uruguay. Cómo Kunz Global desarrolla empresas especializadas en agricultura, software, comercio y servicios — y por qué van juntas.",
    },
    contact: {
      title: "Contacto — Kunz Global",
      description: "Póngase en contacto con Kunz Global por alianzas, consultas comerciales o preguntas sobre una de nuestras empresas.",
    },
    legal: { title: "Aviso legal — Kunz Global", description: "Aviso legal e información del titular de kunzglobal.com." },
    privacy: { title: "Política de privacidad — Kunz Global", description: "Cómo trata kunzglobal.com los datos personales." },
    terms: { title: "Términos y condiciones — Kunz Global", description: "Términos y condiciones generales de Kunz Global." },
    notFound: { title: "Página no encontrada — Kunz Global", description: "La página solicitada no existe." },
  },
  nav: {
    businesses: "Empresas",
    about: "Nosotros",
    vision: "Visión",
    contact: "Contacto",
    menu: "Menú",
    close: "Cerrar",
    language: "Idioma",
    skip: "Saltar al contenido",
    home: "Kunz Global — inicio",
  },
  hero: {
    eyebrow: "Grupo empresarial · Uruguay",
    title: ["Un grupo. Varias empresas.", "Una visión."],
    lead: "Kunz Global desarrolla y opera empresas especializadas en agricultura, tecnología, comercio internacional y servicios para empresas.",
    ctaPrimary: "Conocer nuestras empresas",
    ctaSecondary: "Sobre Kunz Global",
    sectors: ["Agricultura", "Software", "Comercio internacional", "Tecnología de ventas", "Seguros", "Servicios para empresas"],
    networkAlt: "Red abstracta: Kunz Global en el centro, conectado con sus áreas de negocio.",
    scroll: "Desplazar",
  },
  group: {
    eyebrow: "El grupo",
    title: ["Una plataforma para construir", "empresas especializadas."],
    lead: "Kunz Global identifica oportunidades, desarrolla modelos de negocio y construye las empresas que los llevan adelante.",
    body: "Cada empresa tiene su propia marca, su propio mercado y su propio foco. El grupo las conecta — con tecnología compartida, experiencia operativa y una mirada internacional.",
    facts: [
      { label: "Base", value: "San José, Uruguay" },
      { label: "Portafolio", value: "Seis empresas activas" },
      { label: "Sectores", value: "Agricultura · Tecnología · Comercio · Seguros · Ventas" },
      { label: "Idiomas de trabajo", value: "English · Español · Deutsch · Português" },
    ],
  },
  portfolio: {
    eyebrow: "Portafolio",
    title: ["Nuestras", "empresas."],
    lead: "Seis marcas, cada una especializada en su área. Construidas y operadas dentro del grupo.",
    viewAll: "Todas las empresas en detalle",
    external: "se abre en una pestaña nueva",
    siteLang: { en: "sitio en inglés", es: "sitio en español", de: "sitio en alemán", pt: "sitio en portugués" },
    agralonFlow: ["Consulta", "Planificación", "Aplicación", "Informe", "Factura"],
    sampleData: "Vista del producto con datos de ejemplo",
    renvoraFlow: ["Investigación", "Contacto", "Seguimiento"],
  },
  businesses: {
    agrotech: {
      category: "Tecnología agrícola",
      short: "Operación de drones agrícolas y servicios de aplicación de precisión para productores en Uruguay.",
      offer: "Aplicaciones con drones para establecimientos agropecuarios en Uruguay: pulverización, siembra al voleo y fertilizante sólido desde el aire, también en zonas de difícil acceso para la maquinaria terrestre.",
      cta: "Ver servicios con drones",
      long: "Kunz Agrotech es el servicio de drones agrícolas del grupo. Con un DJI Agras T100 aplica fitosanitarios, siembra al voleo y distribuye fertilizante sólido para productores en Uruguay, también en bajos y sectores con problemas de piso donde la maquinaria convencional tiene dificultades. Cada trabajo se configura según el cultivo, el producto y las condiciones del lote, y se planifica junto con los productores y sus ingenieros agrónomos.",
      focus: ["Pulverización", "Siembra al voleo", "Fertilizante sólido", "Zonas de difícil acceso"],
    },
    agralon: {
      category: "Plataforma de software",
      short: "La plataforma operativa para prestadores de servicios agrícolas y operadores de drones — de la primera consulta a la factura.",
      offer: "Software para prestadores de servicios agrícolas y operadores de drones: un solo flujo desde la consulta del cliente, pasando por la planificación y el trabajo en campo, hasta el informe y la factura.",
      cta: "Descubrir Agralon",
      long: "Agralon reúne el trabajo diario de las empresas de servicios agrícolas en un solo sistema: consultas, clientes y campos, planificación de pilotos y equipos con control del clima, la app del piloto para el trabajo en campo (también sin señal), informes de aplicación, presupuestos, facturas y cobros. Nació de la operación con drones de Kunz Agrotech y funciona con cualquier marca de dron.",
      focus: ["Consultas y trabajos", "Clientes y campos", "Planificación y clima", "App del piloto", "Informes", "Presupuestos y facturas"],
      status: "Acceso anticipado abierto",
    },
    sourcing: {
      category: "Comercio internacional y abastecimiento",
      short: "Conecta proveedores de Uruguay con compradores internacionales. Foco actual: lana y materias primas agrícolas.",
      offer: "Conecta proveedores uruguayos con compradores B2B internacionales. Foco actual: lana, en tops peinados y lana lavada producidos a pedido.",
      cta: "Ver la oferta de sourcing",
      long: "Kunz Sourcing es la empresa comercial del grupo y el interlocutor del comprador en Uruguay. Su área más desarrollada es la lana: tops peinados y lana lavada, producidos contra pedidos confirmados en una peinaduría uruguaya establecida y enviados con certificado de laboratorio. Kunz Sourcing acuerda la especificación y coordina la documentación y el embarque. La carne bovina se está desarrollando como segunda área.",
      focus: ["Tops de lana", "Lana lavada", "Exportación desde Uruguay", "Comercio B2B"],
    },
    renvora: {
      category: "Tecnología de ventas",
      short: "Software para generación de leads, prospección y automatización de ventas — IA aplicada al trabajo repetitivo de la venta B2B.",
      offer: "Software para equipos de ventas B2B: investiga empresas adecuadas, redacta el primer mensaje y sostiene los seguimientos. Su equipo decide cuánto funciona de forma automática.",
      cta: "Conocer Renvora",
      long: "Renvora es el software de ventas del grupo. Aprende qué vende una empresa y a quién, encuentra y prioriza prospectos adecuados, redacta el contacto y sostiene los seguimientos, mientras el equipo decide cuánto funciona por sí solo. Renvora está en desarrollo, se usa primero en las marcas propias del grupo y se abre a un número reducido de empresas B2B mediante acceso anticipado.",
      focus: ["Investigación de prospectos", "Contacto", "Seguimientos", "Pipeline de ventas"],
      status: "En desarrollo · acceso anticipado",
    },
    versicherung: {
      category: "Seguros y soluciones de riesgo",
      short: "El área de seguros dentro del ecosistema Kunz — basada en la confianza, la continuidad y relaciones de largo plazo con los clientes.",
      offer: "El área de seguros del grupo Kunz. Los detalles de la oferta actual se brindan a pedido; Kunz Global deriva las consultas personalmente.",
      cta: "Contactar al área de seguros",
      long: "Kunz Versicherung es el área de seguros dentro del grupo Kunz. Los detalles de la oferta actual se brindan a pedido. Envíe su consulta a través de Kunz Global; se deriva personalmente.",
      focus: ["Seguros", "Consultas a través de Kunz Global"],
    },
    akquise: {
      category: "Ventas B2B y desarrollo de negocios",
      short: "Ventas salientes especializadas para empresas B2B: generación de leads, prospección en frío y agenda de reuniones.",
      offer: "Ventas salientes realizadas para empresas B2B: investigación de empresas objetivo, primer contacto por teléfono y correo, y agenda de reuniones. Un servicio, no un software.",
      cta: "Ver servicios de ventas",
      long: "KunzAkquise realiza la venta saliente de empresas B2B como servicio: perfil de cliente objetivo, investigación de empresas y contactos, primer contacto telefónico tras la aprobación, campañas de correo con seguimientos, calificación y agenda de reuniones. Se entregan los datos de contacto, notas de llamadas o reuniones acordados. Mientras Renvora es un software que un equipo usa por sí mismo, KunzAkquise hace el trabajo para el cliente.",
      focus: ["Investigación de leads", "Prospección telefónica", "Contacto por correo", "Agenda de reuniones"],
    },
  },
  ecosystem: {
    eyebrow: "Ecosistema",
    title: ["Marcas independientes.", "Un grupo conectado."],
    lead: "Lo que aprende una empresa lo aprovechan las demás. La operación en campo da forma al software. La experiencia en ventas abre mercados. El comercio conecta Uruguay con compradores en el exterior.",
    centerLabel: "El grupo",
    centerText: "Kunz Global marca el rumbo, aporta tecnología y experiencia compartidas, y desarrolla nuevos emprendimientos.",
    futureName: "Future Ventures",
    futureCategory: "En desarrollo",
    futureText: "Evaluamos y construimos nuevas empresas de forma continua. Aparecen aquí cuando están listas.",
  },
  featured: {
    eyebrow: "Empresas destacadas",
    title: ["Sustancia,", "empresa por empresa."],
    items: {
      agrotech: {
        kicker: "Kunz Agrotech",
        title: "Un día de trabajo en el campo.",
        text: "Un DJI Agras T100 sobre un rastrojo, con camioneta de apoyo, tanque de agua y tráiler de mezcla. Cada trabajo se configura según el cultivo, el producto y las condiciones del lote, y la cobertura se controla con tarjetas hidrosensibles.",
        alt: "DJI Agras T100 de Kunz Agrotech sobre un rastrojo en Uruguay, con la camioneta de apoyo y un tráiler con tanque de agua y equipo de mezcla.",
      },
      agralon: {
        kicker: "Agralon",
        title: "De la consulta al cobro.",
        text: "Cada trabajo pasa por las mismas etapas. La oficina planifica, el piloto trabaja desde la app, y el informe y la factura se generan con los datos del trabajo.",
        alt: "Agralon con datos de ejemplo: panel con los trabajos del día, clima y mapa del campo en una laptop, y la app del piloto en un teléfono.",
      },
      sourcing: {
        kicker: "Kunz Sourcing",
        title: "Lana de Uruguay, producida a pedido.",
        text: "Los tops peinados y la lana lavada se producen contra pedidos confirmados en una peinaduría establecida en Uruguay. Kunz Sourcing acuerda la especificación con el comprador y coordina la documentación y el embarque.",
        alt: "Tachos con tops de lana peinada en una peinaduría de Uruguay.",
      },
      renvora: {
        kicker: "Renvora",
        title: "Investigación, contacto y seguimiento en un solo ciclo.",
        text: "Renvora encuentra empresas adecuadas, redacta el primer mensaje, sostiene la conversación y lleva las reuniones al pipeline. El producto está en desarrollo; el acceso anticipado está abierto a un número reducido de empresas B2B.",
        alt: "Flujo comercial esquemático, de la investigación a la reunión.",
      },
    },
    renvoraSteps: ["Investigación", "Calificación", "Contacto", "Seguimiento", "Reunión"],
    renvoraCaption: "Ilustración esquemática",
    agralonSteps: ["Consulta", "Coordinación", "Planificación", "Aplicación", "Informe", "Factura", "Cobro"],
    agralonStepsLabel: "El flujo de Agralon",
    sourcingFacts: [
      { term: "Productos", value: "Tops de lana · lana lavada" },
      { term: "Finura", value: "17–30 µm, rango habitual" },
      { term: "Entrega", value: "FOB Montevideo · CIF a pedido" },
    ],
    statusLabel: "Estado",
  },
  principles: {
    eyebrow: "Principios",
    title: ["Lo que conecta", "a nuestras empresas."],
    items: [
      { title: "Tecnología", text: "Usamos tecnología donde cambia la forma de trabajar de una industria tradicional — y vuelve escalable un negocio." },
      { title: "Ejecución", text: "Construimos y operamos. Cada empresa del grupo hace trabajo real para clientes reales." },
      { title: "Mirada internacional", text: "Conectamos oportunidades entre Uruguay, América Latina y mercados de Europa y más allá." },
      { title: "Valor a largo plazo", text: "Construimos empresas para durar: primero una economía sana, después el crecimiento." },
    ],
  },
  uruguay: {
    eyebrow: "Origen",
    title: ["Construido en Uruguay.", "Conectado con el mundo."],
    text: "Uruguay es el lugar desde donde opera el grupo: un país estable, con una base agropecuaria fuerte y acceso abierto a los mercados internacionales. Desde aquí, Kunz Global trabaja con socios y clientes en América Latina y Europa.",
    points: [
      { title: "Base operativa", text: "San José, Uruguay — cerca del campo y del puerto de Montevideo." },
      { title: "Raíces europeas", text: "Origen europeo y vínculos estrechos con los mercados de habla alemana." },
      { title: "Cuatro idiomas", text: "Inglés, español, alemán y portugués en el trabajo diario." },
    ],
    globeAlt: "Globo centrado en el Atlántico Sur con Uruguay marcado y conexiones hacia Europa, América del Norte y Brasil.",
    marker: "Uruguay",
  },
  future: {
    eyebrow: "Visión",
    title: ["Construimos", "lo que viene."],
    text: "Kunz Global evalúa y desarrolla nuevos emprendimientos de forma continua — en industrias donde la tecnología, los mercados en cambio y las oportunidades operativas crean potencial a largo plazo.",
    fields: ["Tecnología", "Agricultura", "Energía", "Infraestructura", "Comercio", "Servicios"],
    note: "Los nuevos emprendimientos se anuncian cuando están operativos. No antes.",
  },
  cta: {
    title: ["Hablemos de lo que", "podemos construir."],
    text: "Para alianzas, consultas comerciales o preguntas sobre una de nuestras empresas.",
    button: "Contactar a Kunz Global",
  },
  businessesPage: {
    eyebrow: "Portafolio",
    title: ["Seis empresas.", "Un grupo."],
    lead: "Cada empresa del portafolio es especializada, tiene marca propia y se opera dentro de Kunz Global.",
    focusLabel: "Foco",
    futureLink: "Ver lo que viene",
  },
  about: {
    eyebrow: "Sobre Kunz Global",
    title: ["Raíces europeas.", "Construido en Uruguay."],
    lead: "Kunz Global es un grupo empresarial que desarrolla y opera empresas especializadas — fundado y dirigido por Stanley Kunz desde San José, Uruguay.",
    story: [
      { title: "Dónde empezó", text: "Kunz Global nació de un origen europeo y de la decisión de construir en Uruguay — un país con un agro fuerte, instituciones estables y espacio para nuevos modelos de negocio." },
      { title: "De la operación a la tecnología", text: "Las primeras empresas fueron operativas: servicios agrícolas en el campo y comercio de productos agrícolas. Trabajar en esas industrias mostró dónde faltaba software. Agralon surgió exactamente de ahí." },
      { title: "Un grupo, varios especialistas", text: "Las ventas y el desarrollo de negocios se convirtieron en empresas propias, junto con seguros y tecnología de ventas. Hoy Kunz Global reúne agricultura, software, comercio internacional y servicios para empresas bajo un mismo techo." },
      { title: "Lo que viene", text: "El grupo está todavía al comienzo de un desarrollo más largo. Se suman nuevos emprendimientos cuando hay una oportunidad real y la capacidad de ejecutarla bien." },
    ],
    approachTitle: "Cómo trabajamos",
    leadership: {
      eyebrow: "Dirección",
      title: "Stanley Kunz",
      role: "Fundador y Director",
      text: "Stanley Kunz dirige Kunz Global y responde personalmente por el rumbo y la calidad de cada empresa del grupo — con interlocutores claros y comunicación directa.",
      photoAlt: "Retrato de Stanley Kunz, fundador y director de Kunz Global.",
    },
    facts: [
      { label: "Sede", value: "San José, Uruguay" },
      { label: "Empresas", value: "Seis marcas activas" },
      { label: "Áreas", value: "Agricultura, software, comercio, seguros, ventas" },
    ],
  },
  contactPage: {
    eyebrow: "Contacto",
    title: ["Iniciemos una", "conversación."],
    lead: "Cuéntenos brevemente de qué se trata. Derivamos su mensaje a la empresa que corresponde y respondemos personalmente.",
    form: {
      name: "Nombre",
      company: "Empresa",
      email: "Correo electrónico",
      area: "Área de interés",
      areaGeneral: "General / Alianzas",
      message: "Mensaje",
      optional: "opcional",
      submit: "Preparar correo",
      note: "Este formulario abre su programa de correo con el mensaje ya preparado. Este sitio no envía ni guarda ningún dato.",
      success: "Su programa de correo debería estar abierto. Si no es así, escríbanos directamente a",
      errorRequired: "Por favor complete este campo.",
      errorEmail: "Por favor ingrese un correo electrónico válido.",
      mailSubject: "Consulta desde kunzglobal.com",
    },
    directTitle: "Contacto directo",
    emailLabel: "Correo",
    phoneLabel: "Teléfono",
    locationLabel: "Ubicación",
    location: "San José, Uruguay",
  },
  footer: {
    tagline: "Un grupo. Varias empresas. Una visión.",
    businesses: "Empresas",
    company: "Grupo",
    legalTitle: "Legal",
    legal: "Aviso legal",
    privacy: "Privacidad",
    terms: "Términos",
    location: "San José, Uruguay",
    rights: "Todos los derechos reservados.",
  },
  notFound: {
    title: "Esta página no existe.",
    text: "Es posible que la dirección haya cambiado con el relanzamiento de kunzglobal.com.",
    back: "Volver al inicio",
  },
  legalOverrides: {
    brandsTitle: "Empresas y sitios web externos",
    brandsText:
      "Este sitio web informa sobre las empresas de Kunz Global. Los siguientes sitios se operan por separado; para sus contenidos rigen sus propios avisos legales:",
    socialTitle: "Teléfono y WhatsApp",
    socialText:
      "Si nos contacta por teléfono o WhatsApp, rigen además las condiciones de privacidad del proveedor respectivo (para WhatsApp: Meta Platforms, Inc.). No tenemos influencia sobre el tratamiento de datos que realiza dicho proveedor.",
    formTitle: "Formulario de contacto",
    formText:
      "El formulario de contacto de este sitio no transmite datos a nosotros ni a terceros. Solo prepara un mensaje en su propio programa de correo; el mensaje se envía cuando usted lo envía desde allí. Este sitio no instala cookies, carga sus tipografías desde su propio servidor y no usa herramientas de análisis.",
    updated: "Última actualización: septiembre de 2026",
  },
};
