import type { Content } from "./types";

export const pt: Content = {
  meta: {
    home: {
      title: "Kunz Global — Um grupo. Várias empresas. Uma visão.",
      description:
        "A Kunz Global é um grupo empresarial que desenvolve e opera empresas especializadas em agricultura, tecnologia, comércio internacional e serviços para empresas. Com base no Uruguai e atuação internacional.",
    },
    businesses: {
      title: "Nossas empresas — Kunz Global",
      description:
        "O portfólio da Kunz Global: Kunz Agrotech, Agralon, Kunz Sourcing, Renvora, Kunz Systems, KunzAkquise e Vomando — marcas independentes, um grupo conectado.",
    },
    about: {
      title: "Sobre — Kunz Global",
      description:
        "Raízes europeias, construído no Uruguai. Como a Kunz Global desenvolve empresas especializadas em agricultura, software, comércio e serviços — e por que elas pertencem ao mesmo grupo.",
    },
    contact: {
      title: "Contato — Kunz Global",
      description: "Entre em contato com a Kunz Global para parcerias, consultas comerciais ou perguntas sobre uma de nossas empresas.",
    },
    legal: { title: "Aviso legal — Kunz Global", description: "Aviso legal e informações do responsável por kunzglobal.com." },
    privacy: { title: "Política de privacidade — Kunz Global", description: "Como kunzglobal.com trata dados pessoais." },
    terms: { title: "Termos e condições — Kunz Global", description: "Termos e condições gerais da Kunz Global." },
    notFound: { title: "Página não encontrada — Kunz Global", description: "A página solicitada não existe." },
  },
  nav: {
    businesses: "Empresas",
    about: "Sobre",
    vision: "Visão",
    contact: "Contato",
    menu: "Menu",
    close: "Fechar",
    language: "Idioma",
    skip: "Ir para o conteúdo",
    home: "Kunz Global — início",
  },
  hero: {
    eyebrow: "Grupo empresarial · Uruguai",
    title: ["Um grupo. Várias empresas.", "Uma visão."],
    lead: "A Kunz Global desenvolve e opera empresas especializadas em agricultura, tecnologia, comércio internacional e serviços para empresas.",
    ctaPrimary: "Conhecer nossas empresas",
    ctaSecondary: "Sobre a Kunz Global",
    sectors: ["Agricultura", "Software", "Comércio internacional", "Tecnologia de vendas", "Tecnologia linguística", "Serviços para empresas"],
    networkAlt: "Rede abstrata: a Kunz Global no centro, conectada às suas áreas de negócio.",
    scroll: "Rolar",
  },
  group: {
    eyebrow: "O grupo",
    title: ["Uma plataforma para construir", "empresas especializadas."],
    lead: "A Kunz Global identifica oportunidades, desenvolve modelos de negócio e constrói as empresas que os colocam em prática.",
    body: "Cada empresa tem sua própria marca, seu próprio mercado e seu próprio foco. O grupo as conecta — com tecnologia compartilhada, experiência operacional e visão internacional.",
    facts: [
      { label: "Base", value: "San José, Uruguai" },
      { label: "Portfólio", value: "Sete empresas ativas" },
      { label: "Setores", value: "Agricultura · Tecnologia · Comércio · Vendas" },
      { label: "Idiomas de trabalho", value: "English · Español · Deutsch · Português" },
    ],
  },
  portfolio: {
    eyebrow: "Portfólio",
    title: ["Nossas", "empresas."],
    lead: "Sete marcas, cada uma especializada em sua área. Construídas e operadas dentro do grupo.",
    viewAll: "Todas as empresas em detalhe",
    external: "abre em uma nova aba",
    siteLang: { en: "site em inglês", es: "site em espanhol", de: "site em alemão", pt: "site em português" },
    agralonFlow: ["Consulta", "Planejamento", "Aplicação", "Relatório", "Fatura"],
    sampleData: "Visão do produto com dados de exemplo",
    renvoraFlow: ["Pesquisa", "Contato", "Follow-up"],
    illustration: "Ilustração",
    systemsModules: ["Plataformas web", "Apps móveis", "Automação", "Fluxos com IA"],
    systemsCaption: "Visão esquemática",
    akquiseSteps: ["Lista de alvos", "Primeiro contato", "Reunião"],
    akquiseCaption: "Processo do serviço",
    vomando: { course: "Espanhol · Uruguai", lesson: "Frases do dia a dia", neutral: "Neutro", local: "Uruguai", meaning: "Você pode me ajudar?", caption: "Visão esquemática do app" },
  },
  businesses: {
    agrotech: {
      category: "Tecnologia agrícola",
      short: "Operação de drones agrícolas e serviços de aplicação de precisão para produtores no Uruguai.",
      offer: "Aplicação com drones para propriedades rurais no Uruguai: pulverização, semeadura a lanço e fertilizante sólido pelo ar, inclusive em áreas de difícil acesso para máquinas terrestres.",
      cta: "Ver serviços com drones",
      long: "A Kunz Agrotech é o serviço de drones agrícolas do grupo. Com um DJI Agras T100, aplica defensivos, faz semeadura a lanço e distribui fertilizante sólido para produtores no Uruguai, inclusive em baixadas e áreas encharcadas onde a maquinaria convencional tem dificuldade. Cada trabalho é configurado conforme a cultura, o produto e as condições do talhão, e planejado com os produtores e seus engenheiros agrônomos.",
      focus: ["Pulverização", "Semeadura a lanço", "Fertilizante sólido", "Áreas de difícil acesso"],
    },
    agralon: {
      category: "Software agrícola",
      short: "A plataforma operacional para prestadores de serviços agrícolas e operadores de drones — da primeira consulta à fatura.",
      offer: "Software para prestadores de serviços agrícolas e operadores de drones: um só fluxo da consulta do cliente, passando pelo planejamento e pelo trabalho em campo, até o relatório e a fatura.",
      cta: "Conhecer a Agralon",
      long: "A Agralon reúne o dia a dia das empresas de serviços agrícolas em um só sistema: consultas, clientes e talhões, planejamento de pilotos e equipamentos com verificação do clima, o app do piloto para o trabalho em campo (inclusive sem sinal), relatórios de aplicação, orçamentos, faturas e pagamentos. Nasceu da operação com drones da Kunz Agrotech e funciona com qualquer marca de drone.",
      focus: ["Consultas e trabalhos", "Clientes e talhões", "Planejamento e clima", "App do piloto", "Relatórios", "Orçamentos e faturas"],
      status: "Acesso antecipado aberto",
    },
    sourcing: {
      category: "Comércio internacional e sourcing",
      short: "Carne bovina e lã Merino do Uruguai para compradores B2B internacionais, originadas na fonte e conduzidas como comércio estruturado.",
      offer: "Carne bovina uruguaia de pasto (grass-fed) para importadores, atacadistas e indústrias, fornecida por frigoríficos exportadores habilitados para a UE. Complementada por lã Merino.",
      cta: "Ver a oferta de sourcing",
      long: "A Kunz Sourcing é a empresa comercial do grupo e o interlocutor do comprador no Uruguai. Seu foco é a carne bovina: cortes premium, cortes para processamento e carne industrial, resfriada ou congelada, fornecida conforme especificação por frigoríficos exportadores uruguaios habilitados para a UE; frigorífico, especificação e documentação são confirmados antes da cotação. A lã Merino complementa a oferta: tops penteados e lã lavada, produzidos sob encomenda em uma penteadora uruguaia estabelecida.",
      focus: ["Carne bovina de pasto", "Cortes premium e para processamento", "Lã Merino", "Exportação a partir do Uruguai"],
    },
    renvora: {
      category: "Tecnologia de vendas",
      short: "Software para geração de leads, prospecção e automação de vendas — IA aplicada ao trabalho repetitivo da venda B2B.",
      offer: "Software para equipes de vendas B2B: pesquisa empresas adequadas, redige a primeira mensagem e mantém os follow-ups. Sua equipe decide quanto roda de forma automática.",
      cta: "Conhecer a Renvora",
      long: "A Renvora é o software de vendas do grupo. Aprende o que uma empresa vende e para quem, encontra e prioriza prospects adequados, redige a abordagem e mantém os follow-ups, enquanto a equipe decide quanto roda sozinho. A Renvora está em desenvolvimento, é usada primeiro nas marcas do próprio grupo e se abre a um número reduzido de empresas B2B por meio de acesso antecipado.",
      focus: ["Pesquisa de prospects", "Abordagem", "Follow-ups", "Pipeline de vendas"],
      status: "Em desenvolvimento · acesso antecipado",
    },
    systems: {
      category: "Software, apps e automação",
      short: "Software sob medida, plataformas web, apps móveis e automação para empresas, e a tecnologia por trás dos produtos do próprio grupo.",
      offer: "Software sob medida, plataformas web, apps móveis e automação de processos, inclusive com fluxos apoiados por IA. Construídos de acordo com a forma como cada empresa trabalha.",
      cta: "Consultar um projeto",
      long: "A Kunz Systems é a área de software e desenvolvimento digital do grupo. Projeta e desenvolve software sob medida, plataformas web, apps móveis, sites corporativos e ferramentas internas, e automatiza processos recorrentes, inclusive com fluxos apoiados por IA. Os produtos do próprio grupo, entre eles Agralon e Renvora, são desenvolvidos pela Kunz Systems. O site próprio está em preparação; as consultas são feitas pela Kunz Global.",
      focus: ["Software sob medida", "Plataformas e sites", "Apps móveis", "Automação de processos e IA", "Ferramentas internas"],
      status: "Site em preparação",
    },
    akquise: {
      category: "Vendas B2B e desenvolvimento de negócios",
      short: "Vendas outbound especializadas para empresas B2B: geração de leads, prospecção ativa e agendamento de reuniões.",
      offer: "Vendas outbound executadas para empresas B2B: pesquisa de empresas-alvo, primeiro contato por telefone e e-mail e agendamento de reuniões. Um serviço, não um software.",
      cta: "Ver serviços de vendas",
      long: "A KunzAkquise realiza a venda outbound de empresas B2B como serviço: perfil de cliente-alvo, pesquisa de empresas e contatos, primeiro contato telefônico após aprovação, campanhas de e-mail com follow-ups, qualificação e agendamento de reuniões. São entregues os dados de contato, notas de ligações ou reuniões combinados. Enquanto a Renvora é um software que a própria equipe usa, a KunzAkquise faz o trabalho para o cliente.",
      focus: ["Pesquisa de leads", "Prospecção por telefone", "Abordagem por e-mail", "Agendamento de reuniões"],
    },
    vomando: {
      category: "Tecnologia para aprender idiomas",
      short: "Um app para aprender um idioma do jeito que ele é falado em um país específico. Primeiro curso: o espanhol do Uruguai.",
      offer: "Um app para aprender um idioma do jeito que ele é realmente falado em um país específico: lições estruturadas, prática de fala e uso regional. Primeiro curso: Espanhol · Uruguai.",
      cta: "Consultar pela Kunz Global",
      long: "A Vomando é o produto de tecnologia de consumo do grupo para o aprendizado de idiomas. Ensina não só o que é gramaticalmente correto, mas também o que soa natural e o que é comum em cada lugar, do neutro ao coloquial. O primeiro curso é o espanhol do Uruguai; outros idiomas e variantes regionais estão previstos. O app foi pensado para lições estruturadas, prática de fala e conversação apoiada por IA, e está em desenvolvimento.",
      focus: ["App móvel", "Lições estruturadas", "Prática de fala", "Idioma regional"],
      status: "Em desenvolvimento",
    },
  },
  ecosystem: {
    eyebrow: "Ecossistema",
    title: ["Marcas independentes.", "Um grupo conectado."],
    lead: "O que uma empresa aprende, as outras aproveitam. A operação em campo dá forma ao software. A experiência em vendas abre mercados. O comércio conecta o Uruguai a compradores no exterior.",
    centerLabel: "O grupo",
    centerText: "A Kunz Global define a direção, fornece tecnologia e experiência compartilhadas e desenvolve novos empreendimentos.",
    futureName: "Future Ventures",
    futureCategory: "Em desenvolvimento",
    futureText: "Novas empresas são avaliadas e construídas continuamente. Aparecem aqui quando estão prontas.",
  },
  featured: {
    eyebrow: "Empresas em destaque",
    title: ["Substância,", "empresa por empresa."],
    items: {
      agrotech: {
        kicker: "Kunz Agrotech",
        title: "Um dia de trabalho no campo.",
        text: "Um DJI Agras T100 em uma área colhida, com caminhonete de apoio, tanque de água e reboque de mistura. Cada trabalho é configurado conforme a cultura, o produto e as condições do talhão, e a cobertura é verificada com cartões hidrossensíveis.",
        alt: "DJI Agras T100 da Kunz Agrotech em uma área colhida no Uruguai, com a caminhonete de apoio e um reboque com tanque de água e equipamento de mistura.",
      },
      agralon: {
        kicker: "Agralon",
        title: "Da consulta ao pagamento.",
        text: "Cada trabalho passa pelas mesmas etapas. O escritório planeja, o piloto trabalha pelo app, e o relatório e a fatura são gerados a partir dos dados do trabalho.",
        alt: "Agralon com dados de exemplo: painel com os trabalhos do dia, clima e mapa do talhão em um laptop, e o app do piloto em um celular.",
      },
      sourcing: {
        kicker: "Kunz Sourcing",
        title: "Carne bovina e lã Merino do Uruguai.",
        text: "A Kunz Sourcing fornece carne bovina conforme a especificação do comprador por frigoríficos exportadores uruguaios habilitados para a UE, e lã Merino em tops penteados e lã lavada produzidos sob encomenda. Especificação, documentação e embarque são coordenados a partir do Uruguai.",
        alt: "Ilustração: gado no pasto no Uruguai; foto inserida: tops de lã penteada em uma penteadora uruguaia.",
      },
      renvora: {
        kicker: "Renvora",
        title: "Pesquisa, abordagem e follow-up em um só ciclo.",
        text: "A Renvora encontra empresas adequadas, redige a primeira mensagem, mantém a conversa e leva as reuniões ao pipeline. O produto está em desenvolvimento; o acesso antecipado está aberto a um número reduzido de empresas B2B.",
        alt: "Fluxo comercial esquemático, da pesquisa à reunião.",
      },
    },
    renvoraSteps: ["Pesquisa", "Qualificação", "Abordagem", "Follow-up", "Reunião"],
    renvoraCaption: "Ilustração esquemática",
    agralonSteps: ["Consulta", "Coordenação", "Planejamento", "Aplicação", "Relatório", "Fatura", "Pagamento"],
    agralonStepsLabel: "O fluxo da Agralon",
    sourcingFacts: [
      { term: "Carne bovina", value: "Cortes premium, para processamento e industriais · resfriada ou congelada" },
      { term: "Fornecimento", value: "Frigoríficos exportadores uruguaios habilitados para a UE" },
      { term: "Lã Merino", value: "Tops de lã · lã lavada, sob encomenda" },
    ],
    statusLabel: "Status",
  },
  principles: {
    eyebrow: "Princípios",
    title: ["O que conecta", "nossas empresas."],
    items: [
      { title: "Tecnologia", text: "Usamos tecnologia onde ela muda a forma de trabalhar de um setor tradicional — e torna um negócio escalável." },
      { title: "Execução", text: "Construímos e operamos. Cada empresa do grupo faz trabalho real para clientes reais." },
      { title: "Visão internacional", text: "Conectamos oportunidades entre o Uruguai, a América Latina e mercados da Europa e além." },
      { title: "Valor de longo prazo", text: "Construímos empresas para durar: primeiro uma economia sólida, depois o crescimento." },
    ],
  },
  uruguay: {
    eyebrow: "Origem",
    title: ["Construído no Uruguai.", "Conectado ao mundo."],
    text: "O Uruguai é o lugar de onde o grupo opera: um país estável, com forte base agropecuária e acesso aberto aos mercados internacionais. Daqui, a Kunz Global trabalha com parceiros e clientes na América Latina e na Europa.",
    points: [
      { title: "Base operacional", text: "San José, Uruguai — perto do campo e do porto de Montevidéu." },
      { title: "Raízes europeias", text: "Origem europeia e vínculos estreitos com os mercados de língua alemã." },
      { title: "Quatro idiomas", text: "Inglês, espanhol, alemão e português no dia a dia dos negócios." },
    ],
    globeAlt: "Globo centrado no Atlântico Sul com o Uruguai marcado e conexões em direção à Europa, à América do Norte e ao Brasil.",
    marker: "Uruguai",
  },
  future: {
    eyebrow: "Visão",
    title: ["Construímos", "o que vem a seguir."],
    text: "A Kunz Global avalia e desenvolve novos empreendimentos de forma contínua — em setores onde tecnologia, mercados em transformação e oportunidades operacionais criam potencial de longo prazo.",
    fields: ["Tecnologia", "Agricultura", "Energia", "Infraestrutura", "Comércio", "Serviços"],
    note: "Novos empreendimentos são anunciados quando estão em operação. Não antes.",
  },
  cta: {
    title: ["Vamos conversar sobre", "o que podemos construir."],
    text: "Para parcerias, consultas comerciais ou perguntas sobre uma de nossas empresas.",
    button: "Falar com a Kunz Global",
  },
  businessesPage: {
    eyebrow: "Portfólio",
    title: ["Sete empresas.", "Um grupo."],
    lead: "Cada empresa do portfólio é especializada, tem marca própria e é operada dentro da Kunz Global.",
    focusLabel: "Foco",
    futureLink: "Ver o que vem a seguir",
  },
  about: {
    eyebrow: "Sobre a Kunz Global",
    title: ["Raízes europeias.", "Construído no Uruguai."],
    lead: "A Kunz Global é um grupo empresarial que desenvolve e opera empresas especializadas — fundado e dirigido por Stanley Kunz a partir de San José, Uruguai.",
    story: [
      { title: "Onde começou", text: "A Kunz Global nasceu de uma origem europeia e da decisão de construir no Uruguai — um país com agro forte, instituições estáveis e espaço para novos modelos de negócio." },
      { title: "Da operação à tecnologia", text: "As primeiras empresas foram operacionais: serviços agrícolas em campo e comércio de produtos agrícolas. Trabalhar nesses setores mostrou onde faltava software. A Agralon surgiu exatamente daí." },
      { title: "Um grupo, vários especialistas", text: "Vendas e desenvolvimento de negócios tornaram-se empresas próprias; depois vieram tecnologia de vendas, desenvolvimento de software e tecnologia para aprender idiomas. Hoje a Kunz Global reúne agricultura, software, comércio internacional e serviços para empresas sob o mesmo teto." },
      { title: "O que vem a seguir", text: "O grupo ainda está no começo de um desenvolvimento mais longo. Novos empreendimentos entram quando há uma oportunidade real e a capacidade de executá-la bem." },
    ],
    approachTitle: "Como trabalhamos",
    leadership: {
      eyebrow: "Direção",
      title: "Stanley Kunz",
      role: "Fundador e Diretor",
      text: "Stanley Kunz dirige a Kunz Global e responde pessoalmente pela direção e pela qualidade de cada empresa do grupo — com interlocutores claros e comunicação direta.",
      photoAlt: "Retrato de Stanley Kunz, fundador e diretor da Kunz Global.",
    },
    facts: [
      { label: "Sede", value: "San José, Uruguai" },
      { label: "Empresas", value: "Sete marcas ativas" },
      { label: "Áreas", value: "Agricultura, software, comércio, vendas" },
    ],
  },
  contactPage: {
    eyebrow: "Contato",
    title: ["Vamos iniciar uma", "conversa."],
    lead: "Conte-nos brevemente do que se trata. Encaminhamos sua mensagem à empresa certa e respondemos pessoalmente.",
    form: {
      name: "Nome",
      company: "Empresa",
      email: "E-mail",
      area: "Área de interesse",
      areaGeneral: "Geral / Parcerias",
      message: "Mensagem",
      optional: "opcional",
      submit: "Preparar e-mail",
      note: "Este formulário abre o seu programa de e-mail com a mensagem já preparada. Este site não envia nem armazena nenhum dado.",
      success: "Seu programa de e-mail deve estar aberto agora. Caso contrário, escreva diretamente para",
      errorRequired: "Por favor, preencha este campo.",
      errorEmail: "Por favor, informe um e-mail válido.",
      mailSubject: "Consulta via kunzglobal.com",
    },
    directTitle: "Contato direto",
    emailLabel: "E-mail",
    phoneLabel: "Telefone",
    locationLabel: "Localização",
    location: "San José, Uruguai",
  },
  footer: {
    tagline: "Um grupo. Várias empresas. Uma visão.",
    businesses: "Empresas",
    company: "Grupo",
    legalTitle: "Legal",
    legal: "Aviso legal",
    privacy: "Privacidade",
    terms: "Termos",
    location: "San José, Uruguai",
    rights: "Todos os direitos reservados.",
  },
  notFound: {
    title: "Esta página não existe.",
    text: "O endereço pode ter mudado com o relançamento de kunzglobal.com.",
    back: "Voltar ao início",
  },
  legalOverrides: {
    brandsTitle: "Empresas e sites externos",
    brandsText:
      "Este site informa sobre as empresas da Kunz Global. Os sites a seguir são operados separadamente; para seus conteúdos valem os respectivos avisos legais:",
    socialTitle: "Telefone e WhatsApp",
    socialText:
      "Se você nos contatar por telefone ou WhatsApp, aplicam-se adicionalmente as condições de privacidade do respectivo provedor (para o WhatsApp: Meta Platforms, Inc.). Não temos influência sobre o tratamento de dados realizado por esse provedor.",
    formTitle: "Formulário de contato",
    formText:
      "O formulário de contato deste site não transmite dados a nós nem a terceiros. Ele apenas prepara uma mensagem no seu próprio programa de e-mail; a mensagem é enviada quando você a envia de lá. Este site não instala cookies, carrega suas fontes do próprio servidor e não utiliza ferramentas de análise.",
    updated: "Última atualização: setembro de 2026",
  },
};
