// Builds the dotted globe of the "Built in Uruguay" section as static SVG path data.
// Land comes from Natural Earth 1:110m (world-atlas); the result is committed, so the
// site itself ships no map library. Usage: node scripts/build-globe.mjs
import fs from "node:fs";
import { createRequire } from "node:module";
import { geoOrthographic, geoPath, geoContains, geoDistance, geoInterpolate, geoGraticule10 } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const world = require("world-atlas/land-110m.json");
const land = feature(world, world.objects.land);

const SIZE = 600;
const R = 286;
const CENTER = [-32, -8]; // South Atlantic: South America, Africa and Europe in view
const projection = geoOrthographic().scale(R).translate([SIZE / 2, SIZE / 2]).rotate([-CENTER[0], -CENTER[1]]).clipAngle(90);
const path = geoPath(projection);
const r1 = (n) => Math.round(n * 10) / 10;

// Land dots on a grid whose longitudinal step widens towards the poles.
const STEP = 2.1;
const dots = [];
for (let lat = -84; lat <= 84; lat += STEP) {
  const lonStep = STEP / Math.max(Math.cos((lat * Math.PI) / 180), 0.12);
  for (let lon = -180; lon < 180; lon += lonStep) {
    const p = [lon, lat];
    if (geoDistance(p, CENTER) > Math.PI / 2 - 0.04) continue;
    if (!geoContains(land, p)) continue;
    const [x, y] = projection(p);
    dots.push(`M${r1(x)} ${r1(y)}h0`);
  }
}

const ORIGIN = [-56.7, -34.3]; // San José, Uruguay
const TARGETS = { europe: [8.7, 50.1], northAmerica: [-74, 40.7], brazil: [-46.6, -23.5] };

// Arcs bow away from the globe's centre, perpendicular to their chord, so short ones still read as arcs.
function arc(to) {
  const at = geoInterpolate(ORIGIN, to);
  const [x0, y0] = projection(ORIGIN);
  const [x1, y1] = projection(to);
  const len = Math.hypot(x1 - x0, y1 - y0);
  let nx = -(y1 - y0) / len;
  let ny = (x1 - x0) / len;
  const mx = (x0 + x1) / 2 - SIZE / 2;
  const my = (y0 + y1) / 2 - SIZE / 2;
  if (nx * mx + ny * my < 0) { nx = -nx; ny = -ny; }
  const bow = len * 0.16;
  const pts = [];
  for (let i = 0; i <= 48; i++) {
    const t = i / 48;
    const [x, y] = projection(at(t));
    const k = Math.sin(Math.PI * t) * bow;
    pts.push(`${r1(x + nx * k)} ${r1(y + ny * k)}`);
  }
  return `M${pts.join("L")}`;
}

const out = {
  size: SIZE,
  radius: R,
  dots: dots.join(""),
  graticule: path(geoGraticule10()).replace(/(\.\d)\d+/g, "$1"),
  origin: projection(ORIGIN).map(r1),
  arcs: Object.fromEntries(Object.entries(TARGETS).map(([k, v]) => [k, { d: arc(v), end: projection(v).map(r1) }])),
};

fs.mkdirSync("src/render/generated", { recursive: true });
fs.writeFileSync(
  "src/render/generated/globe.ts",
  `// Generated by scripts/build-globe.mjs — do not edit.\nexport const GLOBE = ${JSON.stringify(out)} as const;\n`
);
console.log("dots", dots.length, "bytes", JSON.stringify(out).length);
